(function(){
'use strict';
const V=window.Voidlands,B=V.B,CS=V.CHUNK_SIZE,H=V.WORLD_HEIGHT;
const index=(x,y,z)=>y*CS*CS+z*CS+x;

/* New combat and utility items. */
Object.assign(V.Items,{
  breeze_rod:{key:'breeze_rod',name:'Breeze Rod',maxStack:64,category:'materials',icon:'breeze_rod'},
  heavy_core:{key:'heavy_core',name:'Heavy Core',maxStack:64,category:'materials',icon:'heavy_core'},
  wind_charge:{key:'wind_charge',name:'Wind Charge',maxStack:64,category:'combat',icon:'wind_charge',projectile:'wind'},
  ender_pearl:{key:'ender_pearl',name:'Ender Pearl',maxStack:16,category:'utility',icon:'ender_pearl',projectile:'pearl'},
  mace:{key:'mace',name:'Mace',maxStack:1,category:'combat',icon:'mace',tool:'mace',tier:4,speed:.8,durability:500,damage:6,enchantments:['Wind Burst III'],description:'Smash attacks gain damage from falling and launch you upward after a successful hit.'}
});
V.Recipes.push(
  {type:'shaped',shape:[' A ','ACA',' A '],map:{A:'astral_crystal',C:'cinder_shard'},out:['breeze_rod',1]},
  {type:'shaped',shape:['III','IAI','III'],map:{I:'iron_ingot',A:'astral_crystal'},out:['heavy_core',1]},
  {type:'shapeless',in:{breeze_rod:1,coal:1},out:['wind_charge',4]},
  {type:'shaped',shape:['H','R'],map:{H:'heavy_core',R:'breeze_rod'},out:['mace',1]}
);

/* Pixel icons for items added after the base atlas was constructed. */
const oldItemCanvas=V.createItemCanvas;
V.createItemCanvas=function(key,size=32){
  if(!['breeze_rod','heavy_core','wind_charge','ender_pearl','mace'].includes(key))return oldItemCanvas(key,size);
  const small=document.createElement('canvas');small.width=small.height=16;const c=small.getContext('2d',{alpha:true});c.imageSmoothingEnabled=false;
  const rect=(x,y,w,h,color)=>{c.fillStyle=color;c.fillRect(x,y,w,h)};
  const line=(x0,y0,x1,y1,color,w=1)=>{c.strokeStyle=color;c.lineWidth=w;c.beginPath();c.moveTo(x0+.5,y0+.5);c.lineTo(x1+.5,y1+.5);c.stroke()};
  if(key==='breeze_rod'){line(4,14,11,2,'#7ad9dc',3);line(5,13,12,1,'#d9ffff',1);rect(8,5,4,3,'#3f9da8');rect(3,10,3,3,'#b8f4ef')}
  if(key==='heavy_core'){rect(3,3,10,10,'#2f343b');rect(4,4,8,8,'#59636c');rect(6,5,4,4,'#b9c7cf');rect(7,6,2,2,'#eff8fb');rect(3,7,2,3,'#1e2329')}
  if(key==='wind_charge'){rect(4,4,8,8,'#75d8e3');rect(5,3,6,10,'#b9f7f5');rect(3,6,10,5,'#66bac7');rect(6,5,4,4,'#efffff');rect(7,7,2,2,'#4c879d')}
  if(key==='ender_pearl'){rect(4,4,8,8,'#0d5f53');rect(5,3,6,10,'#1b917c');rect(3,6,10,5,'#167968');rect(6,5,4,4,'#56e2c2');rect(8,6,2,2,'#b7fff0')}
  if(key==='mace'){line(5,15,9,7,'#6e5132',3);line(6,14,10,6,'#b4864d',1);rect(5,2,8,6,'#3f4850');rect(4,3,9,4,'#66737c');rect(6,2,5,2,'#cbd7dc');rect(10,5,3,3,'#252b31')}
  const out=document.createElement('canvas');out.width=out.height=size;const o=out.getContext('2d',{alpha:true});o.imageSmoothingEnabled=false;o.drawImage(small,0,0,16,16,0,0,size,size);return out;
};
V.createItemTexture=function(key,size=64){const tex=new THREE.CanvasTexture(V.createItemCanvas(key,size));tex.magFilter=THREE.NearestFilter;tex.minFilter=THREE.NearestFilter;tex.generateMipmaps=false;if('encoding' in tex&&THREE.sRGBEncoding)tex.encoding=THREE.sRGBEncoding;return tex};
V.iconCache={};

/* Standard 64x64 Minecraft skin support. */
let defaultSkinCache=null;
function defaultSkin(){
  if(defaultSkinCache)return defaultSkinCache;const c=document.createElement('canvas');c.width=c.height=64;const x=c.getContext('2d',{alpha:true});x.imageSmoothingEnabled=false;
  const f=(a,b,c1,d,col)=>{x.fillStyle=col;x.fillRect(a,b,c1,d)};
  f(0,0,64,64,'rgba(0,0,0,0)');
  f(8,8,8,8,'#d49b78');f(0,8,8,8,'#bd7f61');f(16,8,8,8,'#e4b08c');f(24,8,8,8,'#a96e54');f(8,0,8,8,'#5b3828');f(16,0,8,8,'#9a684c');
  f(20,20,8,12,'#315873');f(16,20,4,12,'#244256');f(28,20,4,12,'#3f6e8d');f(32,20,8,12,'#1d3444');f(20,16,8,4,'#4d83a0');f(28,16,8,4,'#203b4d');
  f(44,20,4,12,'#315d7c');f(40,20,4,12,'#24465f');f(52,20,4,12,'#3e7192');f(56,20,4,12,'#1e394d');f(44,16,4,4,'#5290ad');f(48,16,4,4,'#172f42');
  f(36,52,4,12,'#315d7c');f(32,52,4,12,'#24465f');f(40,52,4,12,'#3e7192');f(44,52,4,12,'#1e394d');f(36,48,4,4,'#5290ad');f(40,48,4,4,'#172f42');
  f(4,20,4,12,'#263240');f(0,20,4,12,'#1a232e');f(12,20,4,12,'#354555');f(16,20,4,12,'#1e2833');f(4,16,4,4,'#46596c');f(8,16,4,4,'#151d26');
  f(20,52,4,12,'#263240');f(16,52,4,12,'#1a232e');f(24,52,4,12,'#354555');f(28,52,4,12,'#1e2833');f(20,48,4,4,'#46596c');f(24,48,4,4,'#151d26');
  defaultSkinCache=c.toDataURL('image/png');return defaultSkinCache;
}
const skinRegions={
 head:[[0,8,8,8],[16,8,8,8],[8,0,8,8],[16,0,8,8],[8,8,8,8],[24,8,8,8]],
 head2:[[32,8,8,8],[48,8,8,8],[40,0,8,8],[48,0,8,8],[40,8,8,8],[56,8,8,8]],
 body:[[16,20,4,12],[28,20,4,12],[20,16,8,4],[28,16,8,4],[20,20,8,12],[32,20,8,12]],
 body2:[[16,36,4,12],[28,36,4,12],[20,32,8,4],[28,32,8,4],[20,36,8,12],[32,36,8,12]],
 rightArm:[[40,20,4,12],[52,20,4,12],[44,16,4,4],[48,16,4,4],[44,20,4,12],[56,20,4,12]],
 rightArm2:[[40,36,4,12],[52,36,4,12],[44,32,4,4],[48,32,4,4],[44,36,4,12],[56,36,4,12]],
 leftArm:[[32,52,4,12],[40,52,4,12],[36,48,4,4],[40,48,4,4],[36,52,4,12],[44,52,4,12]],
 leftArm2:[[48,52,4,12],[56,52,4,12],[52,48,4,4],[56,48,4,4],[52,52,4,12],[60,52,4,12]],
 rightLeg:[[0,20,4,12],[12,20,4,12],[4,16,4,4],[8,16,4,4],[4,20,4,12],[16,20,4,12]],
 rightLeg2:[[0,36,4,12],[12,36,4,12],[4,32,4,4],[8,32,4,4],[4,36,4,12],[16,36,4,12]],
 leftLeg:[[16,52,4,12],[24,52,4,12],[20,48,4,4],[24,48,4,4],[20,52,4,12],[28,52,4,12]],
 leftLeg2:[[0,52,4,12],[8,52,4,12],[4,48,4,4],[8,48,4,4],[4,52,4,12],[12,52,4,12]]
};
function setUV(geo,regions){const uv=geo.attributes&&geo.attributes.uv;if(!uv||!uv.array)return;for(let face=0;face<6;face++){const r=regions[face],u0=r[0]/64,u1=(r[0]+r[2])/64,v0=1-(r[1]+r[3])/64,v1=1-r[1]/64,off=face*8;uv.array[off]=u0;uv.array[off+1]=v1;uv.array[off+2]=u1;uv.array[off+3]=v1;uv.array[off+4]=u0;uv.array[off+5]=v0;uv.array[off+6]=u1;uv.array[off+7]=v0}uv.needsUpdate=true}
function skinTexture(settings){const url=settings.skinData||defaultSkin();if(THREE.TextureLoader){const t=new THREE.TextureLoader().load(url);t.magFilter=THREE.NearestFilter;t.minFilter=THREE.NearestFilter;t.generateMipmaps=false;if('encoding' in t&&THREE.sRGBEncoding)t.encoding=THREE.sRGBEncoding;return t}return new THREE.CanvasTexture(document.createElement('canvas'))}
function skinPart(texture,part,w,h,d,view=false,overlay=false){const geo=new THREE.BoxGeometry(w,h,d);setUV(geo,skinRegions[part+(overlay?'2':'')]);const opts={map:texture,transparent:overlay,alphaTest:overlay?.02:0,side:THREE.FrontSide};const mat=view?new THREE.MeshBasicMaterial(Object.assign({toneMapped:false,depthTest:true,depthWrite:true},opts)):new THREE.MeshLambertMaterial(opts);const mesh=new THREE.Mesh(geo,mat);mesh.castShadow=!view;mesh.receiveShadow=!view;return mesh}
function dispose(root){if(!root)return;root.traverse(o=>{if(o.geometry&&o.geometry.dispose)o.geometry.dispose();if(o.material){const list=Array.isArray(o.material)?o.material:[o.material];for(const m of list)if(m&&m.dispose)m.dispose()}})}
class SkinPlayerVisuals{
 constructor(game){this.game=game;this.swingTime=0;this.swingLength=.32;this.currentKey=null;this.build();}
 build(){this.skin=skinTexture(this.game.settings);this.createFirstPerson();this.createThirdPerson();this.refreshHeldItem(true)}
 createFirstPerson(){if(!this.game.viewScene)this.game.viewScene=new THREE.Scene();if(!this.game.viewCamera){this.game.viewCamera=new THREE.PerspectiveCamera(this.game.settings.fov||75,(typeof innerWidth==='number'?innerWidth:1280)/(typeof innerHeight==='number'?innerHeight:720),.01,12);this.game.viewScene.add(this.game.viewCamera)}const slim=this.game.settings.skinModel==='slim',root=this.firstPerson=new THREE.Group();root.name='FirstPersonViewModel';root.position.set(.48,-.40,-.82);this.game.viewCamera.add(root);const arm=skinPart(this.skin,'rightArm',slim?.18:.22,.72,.22,true,false);arm.position.set(.04,-.08,.03);arm.rotation.z=-.12;root.add(arm);const outer=skinPart(this.skin,'rightArm',slim?.188:.23,.735,.23,true,true);outer.position.copy(arm.position);outer.rotation.z=-.12;root.add(outer);this.fpItemAnchor=new THREE.Group();this.fpItemAnchor.position.set(-.04,-.30,-.16);this.fpItemAnchor.rotation.set(-.18,-.18,.08);root.add(this.fpItemAnchor)}
 createThirdPerson(){const slim=this.game.settings.skinModel==='slim',root=this.thirdPerson=new THREE.Group();root.name='PlayerModel';this.game.scene.add(root);this.body=skinPart(this.skin,'body',.58,.72,.3);this.body.position.y=1.05;root.add(this.body);this.bodyOuter=skinPart(this.skin,'body',.595,.735,.315,false,true);this.bodyOuter.position.y=1.05;root.add(this.bodyOuter);this.head=skinPart(this.skin,'head',.5,.5,.5);this.head.position.y=1.66;root.add(this.head);this.headOuter=skinPart(this.skin,'head',.56,.56,.56,false,true);this.headOuter.position.y=1.66;root.add(this.headOuter);const aw=slim?.18:.22;this.leftArm=skinPart(this.skin,'leftArm',aw,.7,.22);this.leftArm.position.set(-.42,1.09,0);root.add(this.leftArm);const la2=skinPart(this.skin,'leftArm',aw+.012,.715,.232,false,true);la2.position.set(0,0,0);this.leftArm.add(la2);this.rightArm=skinPart(this.skin,'rightArm',aw,.7,.22);this.rightArm.position.set(.42,1.09,0);root.add(this.rightArm);const ra2=skinPart(this.skin,'rightArm',aw+.012,.715,.232,false,true);this.rightArm.add(ra2);this.leftLeg=skinPart(this.skin,'leftLeg',.23,.72,.24);this.leftLeg.position.set(-.16,.36,0);root.add(this.leftLeg);const ll2=skinPart(this.skin,'leftLeg',.242,.735,.252,false,true);this.leftLeg.add(ll2);this.rightLeg=skinPart(this.skin,'rightLeg',.23,.72,.24);this.rightLeg.position.set(.16,.36,0);root.add(this.rightLeg);const rl2=skinPart(this.skin,'rightLeg',.242,.735,.252,false,true);this.rightLeg.add(rl2);this.tpItemAnchor=new THREE.Group();this.tpItemAnchor.position.set(0,-.52,-.06);this.tpItemAnchor.rotation.set(-.4,0,-.12);this.rightArm.add(this.tpItemAnchor)}
 makeHeldMesh(key,first){const item=key&&V.Items[key];if(!item)return null;const isBlock=item.blockId!=null&&!V.Blocks[item.blockId].fluid;let geo,mat;if(isBlock){const def=V.Blocks[item.blockId],size=first?.38:.22;geo=new THREE.BoxGeometry(size,size,size);mat=def.textures.map(name=>new THREE.MeshBasicMaterial({map:V.createTileTexture(name,64),transparent:!!def.transparent,alphaTest:def.cutout?.32:0,side:def.transparent?THREE.DoubleSide:THREE.FrontSide,depthTest:true,depthWrite:true,toneMapped:false}))}else{geo=new THREE.PlaneGeometry(first?.54:.3,first?.54:.3);mat=new THREE.MeshBasicMaterial({map:V.createItemTexture(key,64),transparent:true,alphaTest:.08,side:THREE.DoubleSide,depthTest:true,depthWrite:true,toneMapped:false})}const m=new THREE.Mesh(geo,mat);m.renderOrder=6;if(isBlock)m.rotation.set(.25,.65,.08);else m.rotation.set(0,0,-.2);return m}
 clear(anchor){while(anchor.children.length){const c=anchor.children[0];anchor.remove(c);dispose(c)}}
 refreshHeldItem(force=false){const s=this.game.inventory.selectedStack(),key=s&&s.key||null;if(!force&&key===this.currentKey)return;this.currentKey=key;this.clear(this.fpItemAnchor);this.clear(this.tpItemAnchor);if(!key)return;const a=this.makeHeldMesh(key,true),b=this.makeHeldMesh(key,false);if(a)this.fpItemAnchor.add(a);if(b)this.tpItemAnchor.add(b)}
 swing(){this.swingTime=this.swingLength}
 applySkin(){if(this.firstPerson&&this.firstPerson.parent)this.firstPerson.parent.remove(this.firstPerson);if(this.thirdPerson&&this.thirdPerson.parent)this.thirdPerson.parent.remove(this.thirdPerson);dispose(this.firstPerson);dispose(this.thirdPerson);if(this.skin&&this.skin.dispose)this.skin.dispose();this.currentKey=null;this.build()}
 update(dt){const p=this.game.player;if(!p)return;this.swingTime=Math.max(0,this.swingTime-dt);this.refreshHeldItem();const first=p.perspective===0&&!this.game.hudHidden&&!p.dead&&this.game.state!=='destroyed';this.firstPerson.visible=first;this.thirdPerson.visible=p.perspective!==0&&!p.dead;const moving=Math.hypot(p.velocity.x,p.velocity.z)>.25&&p.grounded,bob=moving?Math.sin(p.walkDistance*7.5):0,sway=moving?Math.cos(p.walkDistance*3.75):0,progress=this.swingTime>0?1-this.swingTime/this.swingLength:0,swing=this.swingTime>0?Math.sin(progress*Math.PI):0;this.firstPerson.position.set(.48+bob*.018,-.40+Math.abs(bob)*.018,-.82+sway*.012);this.firstPerson.rotation.set(-swing*.72,swing*.18,-swing*.48);if(p.eating){const eat=Math.sin(p.eatTime*15)*.08;this.firstPerson.position.y=-.29+eat;this.firstPerson.rotation.x=-.35+eat}this.thirdPerson.position.copy(p.position);this.thirdPerson.rotation.y=p.yaw;this.head.rotation.x=-p.pitch;this.headOuter.rotation.x=-p.pitch;const stride=moving?Math.sin(p.walkDistance*5.4)*.72:0;this.leftLeg.rotation.x=stride;this.rightLeg.rotation.x=-stride;this.leftArm.rotation.x=-stride*.75;this.rightArm.rotation.x=stride*.75-swing*1.35;this.rightArm.rotation.z=-swing*.22;if(p.sneaking){this.body.rotation.x=.22;this.bodyOuter.rotation.x=.22;this.head.position.y=this.headOuter.position.y=1.58;this.leftArm.position.y=this.rightArm.position.y=1.02}else{this.body.rotation.x=this.bodyOuter.rotation.x=0;this.head.position.y=this.headOuter.position.y=1.66;this.leftArm.position.y=this.rightArm.position.y=1.09}}
 dispose(){if(this.firstPerson&&this.firstPerson.parent)this.firstPerson.parent.remove(this.firstPerson);if(this.thirdPerson&&this.thirdPerson.parent)this.thirdPerson.parent.remove(this.thirdPerson);dispose(this.firstPerson);dispose(this.thirdPerson);if(this.skin&&this.skin.dispose)this.skin.dispose()}
 destroy(){this.dispose()}
}
V.PlayerVisuals=SkinPlayerVisuals;

/* Deterministic structures and revised dimensions. */
function setLocal(a,x,y,z,id){if(x>=0&&x<CS&&z>=0&&z<CS&&y>0&&y<H)a[index(x,y,z)]=id}
function chest(world,a,cx,cz,x,y,z,loot){setLocal(a,x,y,z,B.CHEST);const slots=Array.from({length:27},()=>null);loot.forEach((s,i)=>slots[i]=V.makeStack(s[0],s[1]));world.blockEntities[V.blockKey(cx*CS+x,y,cz*CS+z)]={type:'chest',slots}}
function topAt(a,x,z){for(let y=H-2;y>1;y--){const d=V.Blocks[a[index(x,y,z)]];if(d&&d.solid)return y}return 1}
function clearBox(a,x0,y0,z0,x1,y1,z1){for(let y=y0;y<=y1;y++)for(let z=z0;z<=z1;z++)for(let x=x0;x<=x1;x++)setLocal(a,x,y,z,B.AIR)}
function house(a,bx,y,bz,w=5,d=5){for(let z=bz;z<bz+d;z++)for(let x=bx;x<bx+w;x++){setLocal(a,x,y-1,z,B.COBBLE);for(let yy=y;yy<y+4;yy++){const wall=x===bx||x===bx+w-1||z===bz||z===bz+d-1;setLocal(a,x,yy,z,wall?B.PLANKS:B.AIR)}setLocal(a,x,y+4,z,B.PLANKS)}setLocal(a,bx+Math.floor(w/2),y,bz,B.DOOR);setLocal(a,bx+1,y+2,bz,B.GLASS);setLocal(a,bx+w-2,y+2,bz,B.GLASS);setLocal(a,bx+Math.floor(w/2),y+1,bz+d-1,B.GLASS)}
function village(world,a,cx,cz){const y=Math.max(topAt(a,4,4),topAt(a,11,10))+1;for(let z=1;z<15;z++)for(let x=7;x<=8;x++)setLocal(a,x,topAt(a,x,z),z,B.GRAVEL);house(a,1,y,2,6,5);house(a,9,y,8,6,5);for(let z=5;z<=9;z++)for(let x=5;x<=9;x++)setLocal(a,x,y-1,z,B.COBBLE);setLocal(a,7,y,7,B.WATER);for(let yy=y;yy<y+3;yy++)for(const p of [[5,5],[9,5],[5,9],[9,9]])setLocal(a,p[0],yy,p[1],B.LOG);chest(world,a,cx,cz,3,y,4,[['bread',4],['iron_ingot',2],['sun_berry',5]])}
function desertTemple(world,a,cx,cz){const y=topAt(a,8,8)+1;for(let z=2;z<14;z++)for(let x=2;x<14;x++){setLocal(a,x,y-1,z,B.SAND);for(let yy=y;yy<y+6;yy++){const wall=x===2||x===13||z===2||z===13;setLocal(a,x,yy,z,wall?B.SAND:B.AIR)}setLocal(a,x,y+6,z,B.SAND)}for(let yy=y+6;yy<y+11;yy++)for(let z=5;z<=10;z++)for(let x=5;x<=10;x++)if(x===5||x===10||z===5||z===10)setLocal(a,x,yy,z,B.SAND);clearBox(a,7,y-1,7,8,y+2,8);chest(world,a,cx,cz,5,y,5,[['gold_ingot',4],['ender_pearl',1],['lumen_crystal',2]]);chest(world,a,cx,cz,10,y,10,[['iron_ingot',5],['wind_charge',3]])}
function tower(world,a,cx,cz){const y=topAt(a,8,8)+1;for(let yy=y;yy<y+10;yy++)for(let z=4;z<=11;z++)for(let x=4;x<=11;x++){const wall=x===4||x===11||z===4||z===11;setLocal(a,x,yy,z,wall?B.COBBLE:B.AIR)}for(let z=3;z<=12;z++)for(let x=3;x<=12;x++)setLocal(a,x,y+10,z,B.COBBLE);setLocal(a,7,y,4,B.DOOR);chest(world,a,cx,cz,8,y+1,8,[['coal',8],['iron_ingot',3],['ender_pearl',1]])}
function cabin(world,a,cx,cz){const y=topAt(a,7,7)+1;house(a,3,y,3,10,8);for(let z=4;z<10;z++)for(let x=4;x<12;x++)if((x+z)%4===0)setLocal(a,x,y+4,z,B.LEAVES);chest(world,a,cx,cz,10,y,8,[['wood_axe',1],['cooked_meat',3],['torch',8]])}
function trialVault(world,a,cx,cz){const surface=topAt(a,8,8),y=Math.max(8,surface-13);clearBox(a,2,y,2,13,y+6,13);for(let yy=y;yy<=y+6;yy++)for(let z=2;z<=13;z++)for(let x=2;x<=13;x++)if(yy===y||yy===y+6||x===2||x===13||z===2||z===13)setLocal(a,x,yy,z,(x+z+yy)%5?B.COBBLE:B.BRICKS);for(const p of [[4,4],[11,4],[4,11],[11,11]])setLocal(a,p[0],y+1,p[1],B.TORCH);chest(world,a,cx,cz,8,y+1,8,[['heavy_core',1],['breeze_rod',2],['wind_charge',8],['mace',1]])}
function mineshaft(world,a,cx,cz){const y=12+Math.floor(V.Noise.hash3(cx,1,cz,world.seed+6021)*16);for(let z=2;z<14;z++){clearBox(a,5,y,z,10,y+3,z);if(z%4===2){for(let yy=y;yy<y+4;yy++){setLocal(a,4,yy,z,B.LOG);setLocal(a,11,yy,z,B.LOG)}for(let x=4;x<=11;x++)setLocal(a,x,y+3,z,B.PLANKS)}}chest(world,a,cx,cz,7,y,11,[['coal',12],['iron_ingot',4],['ender_pearl',1]])}
function applyOverworldStructures(world,a,cx,cz){if(!world.data.structures||cx===0&&cz===0)return;const center=world.terrainInfo(cx*CS+8,cz*CS+8),r=V.Noise.hash3(cx,29,cz,world.seed+5801),trialX=2+(world.seed%4),trialZ=-2-((world.seed>>>4)%4);if(cx===trialX&&cz===trialZ){trialVault(world,a,cx,cz);return}if(r>.994&&center.biome==='dunes'){desertTemple(world,a,cx,cz);return}if(r>.993&&center.biome==='forest'){cabin(world,a,cx,cz);return}if(r>.996&&['plains','scrub'].includes(center.biome)){village(world,a,cx,cz);return}if(r>.997){tower(world,a,cx,cz);return}if(r<.0025)mineshaft(world,a,cx,cz)}
const WP=V.World.prototype;
WP.generateEmberChunk=function(cx,cz){const key=V.chunkKey(cx,cz);if(this.chunkData.has(key))return this.chunkData.get(key);const a=new Uint8Array(CS*H*CS);for(let z=0;z<CS;z++)for(let x=0;x<CS;x++){const wx=cx*CS+x,wz=cz*CS+z,valley=V.Noise.fbm2(wx*.018,wz*.018,this.seed+1701,4)<-.18;for(let y=0;y<H;y++){const floorBed=y<2+Math.floor(V.Noise.hash3(wx,y,wz,this.seed+1702)*3),roofBed=y>H-3-Math.floor(V.Noise.hash3(wx,y,wz,this.seed+1704)*3);let id=B.AIR;if(floorBed||roofBed)id=B.BEDROCK;else{const cave=Math.abs(V.Noise.value3(wx*.048,y*.06,wz*.048,this.seed+1711))+.33*Math.abs(V.Noise.value3(wx*.095,y*.11,wz*.095,this.seed+1717));const open=cave<.47||y<15;if(!open)id=B.EMBERSTONE;else if(y<=14)id=B.LAVA;if(id===B.EMBERSTONE){const r=V.Noise.hash3(wx,y,wz,this.seed+1731);if(y<30&&r>.991)id=B.EMBER_ORE;else if(y>48&&r>.986)id=B.GLOWROCK}else if(id===B.AIR&&valley&&y<28&&thisBlockSolidBelow(a,x,y,z))id=B.ASH}a[index(x,y,z)]=id}}if(this.data.structures){const s=V.Noise.hash3(cx,41,cz,this.seed+1777);if((cx===2&&cz===0)||s>.994)netherFortress(this,a,cx,cz);else if(s<.003)netherBastion(this,a,cx,cz)}this.addGatewayToArray(a,cx,cz,20,B.EMBER_PORTAL);this.chunkData.set(key,a);return a};
function thisBlockSolidBelow(a,x,y,z){if(y<=1)return false;const d=V.Blocks[a[index(x,y-1,z)]];return !!(d&&d.solid)}
function netherFortress(world,a,cx,cz){const y=28;clearBox(a,1,y,5,14,y+5,10);for(let z=4;z<=11;z++)for(let x=0;x<16;x++){setLocal(a,x,y-1,z,B.BRICKS);if(z===4||z===11)for(let yy=y;yy<=y+4;yy++)setLocal(a,x,yy,z,B.BRICKS)}for(let x=0;x<16;x+=5)for(let yy=y;yy<=y+4;yy++){setLocal(a,x,yy,4,B.RIFT_FRAME);setLocal(a,x,yy,11,B.RIFT_FRAME)}chest(world,a,cx,cz,8,y,7,[['breeze_rod',2],['gold_ingot',5],['wind_charge',6]])}
function netherBastion(world,a,cx,cz){const y=18;for(let yy=y;yy<y+13;yy++)for(let z=2;z<14;z++)for(let x=2;x<14;x++){const shell=yy===y||yy===y+12||x===2||x===13||z===2||z===13;setLocal(a,x,yy,z,shell?((x+y+z)%4?B.EMBERSTONE:B.RIFT_FRAME):B.AIR)}chest(world,a,cx,cz,5,y+1,5,[['gold_ingot',8],['obsidian',3],['ender_pearl',2]]);chest(world,a,cx,cz,10,y+1,10,[['heavy_core',1],['cinder_shard',6]])}
WP.generateStarChunk=function(cx,cz){const key=V.chunkKey(cx,cz);if(this.chunkData.has(key))return this.chunkData.get(key);const a=new Uint8Array(CS*H*CS);for(let z=0;z<CS;z++)for(let x=0;x<CS;x++){const wx=cx*CS+x,wz=cz*CS+z,dx=wx-8,dz=wz-8,r=Math.hypot(dx,dz),n=V.Noise.fbm2(wx*.022,wz*.022,this.seed+2703,5),detail=V.Noise.fbm2(wx*.07,wz*.07,this.seed+2711,3);let island=false,top=38,thick=0;if(r<37){island=true;top=40-Math.floor((r/37)*(r/37)*12)+Math.floor(n*2);thick=Math.max(4,15-Math.floor(r/4))}else if(r>48){const density=n+detail*.28;island=density>.16;top=38+Math.floor(n*8);thick=4+Math.floor((density+.25)*7)}if(island)for(let y=Math.max(2,top-thick);y<=top;y++){let id=B.SKY_STONE;const rr=V.Noise.hash3(wx,y,wz,this.seed+2721);if(y<top-2&&rr>.993)id=B.STAR_CRYSTAL_ORE;a[index(x,y,z)]=id}}
  addEndPillars(this,a,cx,cz);if(this.data.structures&&Math.hypot(cx,cz)>4&&V.Noise.hash3(cx,57,cz,this.seed+2781)>.994)endCity(this,a,cx,cz);this.addGatewayToArray(a,cx,cz,42,B.STAR_PORTAL);this.chunkData.set(key,a);return a};
function addEndPillars(world,a,cx,cz){for(let i=0;i<10;i++){const ang=i/10*Math.PI*2,rad=13+(i%4)*4,px=Math.round(8+Math.cos(ang)*rad),pz=Math.round(8+Math.sin(ang)*rad),height=12+(i*7%15),base=39-Math.floor(rad/8);for(let lz=0;lz<CS;lz++)for(let lx=0;lx<CS;lx++){const wx=cx*CS+lx,wz=cz*CS+lz;if((wx-px)*(wx-px)+(wz-pz)*(wz-pz)<=3.2*3.2)for(let y=base;y<=Math.min(H-3,base+height);y++)setLocal(a,lx,y,lz,B.OBSIDIAN)}const lx=px-cx*CS,lz=pz-cz*CS;if(lx>=0&&lx<CS&&lz>=0&&lz<CS)setLocal(a,lx,Math.min(H-2,base+height+1),lz,B.GLOWROCK)}}
function endCity(world,a,cx,cz){let y=topAt(a,8,8)+1;if(y<8)return;for(let yy=y;yy<Math.min(H-2,y+18);yy++){const size=yy<y+5?5:yy<y+13?3:5;for(let z=8-size;z<=8+size;z++)for(let x=8-size;x<=8+size;x++){const shell=x===8-size||x===8+size||z===8-size||z===8+size;setLocal(a,x,yy,z,shell?B.SKY_STONE:B.AIR)}}for(let x=3;x<=13;x++)setLocal(a,x,y+12,8,B.SKY_STONE);chest(world,a,cx,cz,8,y+1,8,[['ender_pearl',4],['astral_crystal',6],['lumen_sword',1]]);chest(world,a,cx,cz,5,y+13,8,[['mace',1],['wind_charge',8]])}
const oldGen=WP.generateChunkData;WP.generateChunkData=function(cx,cz){const a=oldGen.call(this,cx,cz);if(!a.__adventureEnhanced){if(this.dimension==='overworld')applyOverworldStructures(this,a,cx,cz);a.__adventureEnhanced=true}return a};
const oldTerrain=WP.terrainInfo;WP.terrainInfo=function(x,z){if(this.dimension==='emberdeep')return{height:20,biome:V.Noise.fbm2(x*.018,z*.018,this.seed+1701,4)<-.18?'soul_valley':'nether_wastes',temp:1,moisture:-1,continent:1};if(this.dimension==='starreach')return{height:40,biome:'the_end',temp:0,moisture:0,continent:1};return oldTerrain.call(this,x,z)};
WP.dimensionSpawn=function(name=this.dimension){if(name==='emberdeep')return{x:8.5,y:20.05,z:6.5};if(name==='starreach')return{x:8.5,y:42.05,z:6.5};return this.data.spawn||{x:.5,y:V.SEA_LEVEL+20,z:.5}};

/* Projectiles and dimension-specific mobs. */
class Projectile{
 constructor(manager,type,pos,dir){this.manager=manager;this.game=manager.game;this.world=this.game.world;this.type=type;this.position=pos.clone();this.velocity=dir.clone().normalize().multiplyScalar(type==='pearl'?15:21);this.age=0;const geo=new THREE.SphereGeometry(type==='pearl'?.18:.22,8,6),mat=new THREE.MeshBasicMaterial({map:V.createItemTexture(type==='pearl'?'ender_pearl':'wind_charge',32),transparent:true,alphaTest:.05,toneMapped:false});this.mesh=new THREE.Mesh(geo,mat);this.mesh.position.copy(this.position);manager.group.add(this.mesh)}
 update(dt){this.age+=dt;const old=this.position.clone();this.velocity.y-=dt*(this.type==='pearl'?9:1.2);const step=this.velocity.clone().multiplyScalar(dt),dist=Math.hypot(step.x,step.y,step.z),dir=dist?step.clone().multiplyScalar(1/dist):new THREE.Vector3();const hit=this.world.raycast(old,dir,dist+.04);if(hit){this.position.copy(old).addScaledVector(dir,Math.max(0,hit.distance-.05));this.impact(hit);return}this.position.add(step);for(const mob of this.manager.mobs){if(!mob.dead&&mob.position.clone().add(new THREE.Vector3(0,mob.height*.5,0)).distanceTo(this.position)<.75){this.impact({mob,normal:{x:0,y:1,z:0}});return}}this.mesh.position.copy(this.position);this.mesh.rotation.x+=dt*8;this.mesh.rotation.y+=dt*11;if(this.age>(this.type==='pearl'?4:2.5)||this.position.y<-8)this.impact(null)}
 impact(hit){if(this.type==='pearl')this.teleport(hit);else this.burst();this.remove()}
 teleport(hit){const p=this.game.player,target=this.position.clone();if(hit&&hit.normal)target.add(new THREE.Vector3(hit.normal.x,hit.normal.y,hit.normal.z).multiplyScalar(.8));target.y=Math.max(2,target.y);const probe=target.clone();for(let i=0;i<6&&p.collidesAt(probe);i++)probe.y+=1;p.position.copy(probe);p.velocity.set(0,0,0);p.fallStart=null;if(this.game.mode!=='creative')p.damage(5,'was hurt by an Ender Pearl');p.updateCamera();this.game.audio.play('pickup');this.game.ui.toast('Teleported')}
 burst(){const center=this.position.clone(),p=this.game.player,pc=p.position.clone();pc.y+=.8;const pd=pc.distanceTo(center);if(pd<6){const push=pc.sub(center);if(push.distanceTo(new THREE.Vector3())<.2)push.set(0,1,0);push.normalize();const strength=(1-pd/6)*12+3;p.velocity.addScaledVector(push,strength);p.velocity.y=Math.max(p.velocity.y,7+(1-pd/6)*5);p.grounded=false;p.fallStart=null;p.windBurstGrace=1.6}for(const m of this.manager.mobs){const mid=m.position.clone();mid.y+=m.height*.5;const d=mid.distanceTo(center);if(d<6){const k=mid.sub(center).normalize();m.takeDamage(1,k.multiplyScalar(1.8))}}for(let i=0;i<14;i++){const mesh=new THREE.Mesh(new THREE.BoxGeometry(.06,.06,.06),new THREE.MeshBasicMaterial({color:0xa9f4f4,toneMapped:false}));mesh.position.copy(center);this.game.scene.add(mesh);this.game.particles.push({mesh,v:new THREE.Vector3((Math.random()-.5)*9,Math.random()*7-1,(Math.random()-.5)*9),life:.45+Math.random()*.25})}this.game.audio.play('splash')}
 remove(){this.manager.group.remove(this.mesh);if(this.mesh.geometry.dispose)this.mesh.geometry.dispose();if(this.mesh.material.dispose)this.mesh.material.dispose();this.manager.projectiles=this.manager.projectiles.filter(p=>p!==this)}
}
const BaseManager=V.EntityManager;
class AdventureEntityManager extends BaseManager{
 constructor(game){super(game);this.projectiles=[]}
 throwProjectile(type,pos,dir){const p=new Projectile(this,type,pos,dir);this.projectiles.push(p);return p}
 spawn(type,x,y,z){if(type==='endwalker'||type==='blazer'){const m=super.spawn('gloam',x,y,z);m.type=type;m.health=m.maxHealth=type==='endwalker'?40:22;m.speed=type==='endwalker'?2.45:2;m.attackDamage=type==='endwalker'?5:4;m.mesh.traverse(o=>{if(o.material&&o.material.color)o.material.color.set(type==='endwalker'?0x34264f:0xd36a2f)});const baseRemove=m.remove.bind(m);m.die=()=>{if(m.dead)return;m.dead=true;this.game.world.data.stats.mobsDefeated++;if(type==='endwalker')this.drop(V.makeStack('ender_pearl',1+Math.floor(Math.random()*2)),m.position.x,m.position.y+.5,m.position.z);else{this.drop(V.makeStack('breeze_rod',1),m.position.x,m.position.y+.5,m.position.z);if(Math.random()<.5)this.drop(V.makeStack('wind_charge',2),m.position.x,m.position.y+.5,m.position.z)}this.game.player.xp+=type==='endwalker'?8:6;baseRemove()};return m}return super.spawn(type,x,y,z)}
 trySpawn(){const dim=this.game.world.dimension;if(dim==='overworld')return super.trySpawn();if(this.mobs.length>20)return;const p=this.game.player,ang=Math.random()*Math.PI*2,dist=15+Math.random()*22,x=Math.floor(p.position.x+Math.cos(ang)*dist),z=Math.floor(p.position.z+Math.sin(ang)*dist),y=this.game.world.getSurfaceY(x,z);if(y<2||y>H-3||this.game.world.getBlock(x,y,z)!==B.AIR||this.game.world.getBlock(x,y+1,z)!==B.AIR)return;if(dim==='emberdeep')this.spawn(Math.random()<.35?'blazer':'gloam',x+.5,y,z+.5);else this.spawn('endwalker',x+.5,y,z+.5)}
 update(dt){super.update(dt);for(const p of [...this.projectiles])p.update(dt)}
 destroy(){for(const p of [...this.projectiles])p.remove();super.destroy()}
}
V.EntityManager=AdventureEntityManager;

/* Gameplay hooks for projectiles and Wind Burst III. */
const GP=V.Game.prototype,oldUse=GP.useOrPlace,oldBreak=GP.beginBreak,oldFixed=GP.fixedUpdate,oldAtmosphere=GP.updateAtmosphere,oldSwitch=GP.switchDimension;
GP.useOrPlace=function(){const s=this.inventory.selectedStack(),it=s&&V.Items[s.key];if(it&&it.projectile){if((this.projectileCooldown||0)>0)return;this.projectileCooldown=.25;const pos=this.player.eyePosition().addScaledVector(this.player.viewDirection(),.65);this.entities.throwProjectile(it.projectile,pos,this.player.viewDirection());this.visuals.swing('use');this.audio.play('swing');if(this.mode!=='creative'){s.count--;if(s.count<=0)this.inventory.slots[this.inventory.selected]=null}this.ui.refreshHUD();return}return oldUse.call(this)};
GP.beginBreak=function(){const s=this.inventory.selectedStack(),it=s&&V.Items[s.key];if(!it||it.tool!=='mace')return oldBreak.call(this);this.visuals.swing('attack');this.audio.play('swing');if(this.attackCooldown>0)return;const enchant=(id)=>V.enchantLevel?V.enchantLevel(s,id):0,density=enchant('density'),breach=enchant('breach'),wind=Math.max(3,enchant('wind_burst')),dir=this.player.viewDirection(),origin=this.player.eyePosition(),reach=this.mode==='creative'?6:4.5,blockHit=this.world.raycast(origin,dir,reach),entityReach=blockHit?Math.min(reach,Math.max(0,blockHit.distance-.03)):reach,fall=Math.max(0,this.player.fallStart==null?0:this.player.fallStart-this.player.position.y),smash=fall>1.5,scale=2.6+density*.55,damage=this.mode==='creative'?999:6+breach*.8+(smash?Math.min(42,Math.floor((fall-1.5)*scale)):0),hit=this.entities.attackRay(origin,dir,entityReach,damage);if(hit){this.attackCooldown=.62;if(this.mode!=='creative')this.inventory.damageSelected(1);if(smash){this.player.velocity.y=7.5+wind*1.65;this.player.grounded=false;this.player.fallStart=null;this.player.windBurstGrace=1.3+wind*.3;const away=this.player.position.clone().sub(hit.mob.position);away.y=0;if(away.distanceTo(new THREE.Vector3())<.1)away.set(-dir.x,0,-dir.z);away.normalize();this.player.velocity.addScaledVector(away,2+wind*.5);this.ui.toast(`Smash ${Math.round(damage)} damage - Wind Burst ${wind===3?'III':wind}`);for(let i=0;i<18+wind*2;i++){const mesh=new THREE.Mesh(new THREE.BoxGeometry(.07,.07,.07),new THREE.MeshBasicMaterial({color:0xbefcff,toneMapped:false}));mesh.position.copy(hit.mob.position);mesh.position.y+=.8;this.scene.add(mesh);this.particles.push({mesh,v:new THREE.Vector3((Math.random()-.5)*(6+wind),Math.random()*(6+wind),(Math.random()-.5)*(6+wind)),life:.55})}}this.ui.refreshHUD();return}const target=blockHit||this.target;if(target)return oldBreak.call(this)};
GP.fixedUpdate=function(dt){this.projectileCooldown=Math.max(0,(this.projectileCooldown||0)-dt);if(this.player&&this.player.windBurstGrace>0)this.player.windBurstGrace=Math.max(0,this.player.windBurstGrace-dt);return oldFixed.call(this,dt)};
const PP=V.Player.prototype,oldDamage=PP.damage;PP.damage=function(n,reason,continuous){if(this.windBurstGrace>0&&typeof reason==='string'&&reason.startsWith('fell ')){this.windBurstGrace=0;return}return oldDamage.call(this,n,reason,continuous)};
GP.switchDimension=function(target,instant){const result=oldSwitch.call(this,target,instant);this.ui.toast(target==='overworld'?'Returned to the Overworld':target==='emberdeep'?'Entered the Nether':'Entered The End');return result};
GP.updateAtmosphere=function(dt){const result=oldAtmosphere.call(this,dt);if(this.world.dimension==='emberdeep')document.querySelector('#weatherLabel').textContent='THE NETHER';if(this.world.dimension==='starreach')document.querySelector('#weatherLabel').textContent='THE END';return result};

/* UI skin import and enhanced tooltips. */
const UIP=V.UI.prototype,oldBind=UIP.bind,oldAction=UIP.action,oldTooltip=UIP.showTooltip,oldInfo=UIP.renderWorldInfo;
UIP.bind=function(){oldBind.call(this);const input=this.q('#skinFile'),drop=this.q('#skinDropZone');if(input)input.addEventListener('change',()=>this.importSkin(input.files&&input.files[0]));if(drop){drop.addEventListener('dragover',e=>{e.preventDefault();drop.classList.add('drag-over')});drop.addEventListener('dragleave',()=>drop.classList.remove('drag-over'));drop.addEventListener('drop',e=>{e.preventDefault();drop.classList.remove('drag-over');this.importSkin(e.dataTransfer.files&&e.dataTransfer.files[0])})}};
UIP.showSkinScreen=function(returnScreen){this.returnScreen=returnScreen;const s=this.app.settings;this.q('#skinPreview').src=s.skinData||defaultSkin();this.q('#skinNameLabel').textContent=s.skinName||'Default Explorer';this.q('#skinModel').value=s.skinModel||'classic';this.q('#skinFile').value='';this.show('skinsScreen')};
UIP.importSkin=function(file){if(!file)return;if(file.type&&file.type!=='image/png'&&!/\.png$/i.test(file.name)){this.toast('Skin must be a PNG file');return}const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{if(!((img.width===64&&img.height===64)||(img.width===64&&img.height===32))){this.toast('Use a 64x64 or legacy 64x32 skin PNG');return}this.app.settings.skinData=reader.result;this.app.settings.skinName=file.name.replace(/\.png$/i,'')||'Custom Skin';this.app.storage.saveSettings(this.app.settings);this.q('#skinPreview').src=reader.result;this.q('#skinNameLabel').textContent=this.app.settings.skinName;if(this.app.game&&this.app.game.visuals)this.app.game.visuals.applySkin();this.toast('Skin applied')};img.onerror=()=>this.toast('The skin image could not be read');img.src=reader.result};reader.onerror=()=>this.toast('The skin file could not be read');reader.readAsDataURL(file)};
UIP.action=function(a){if(a==='skins'){this.showSkinScreen('titleScreen');return}if(a==='pause-skins'){this.showSkinScreen('pauseScreen');return}if(a==='skin-done'){this.app.settings.skinModel=this.q('#skinModel').value;this.app.storage.saveSettings(this.app.settings);if(this.app.game&&this.app.game.visuals)this.app.game.visuals.applySkin();this.show(this.returnScreen);return}if(a==='skin-reset'){this.app.settings.skinData=null;this.app.settings.skinName='Default Explorer';this.app.settings.skinModel='classic';this.app.storage.saveSettings(this.app.settings);if(this.app.game&&this.app.game.visuals)this.app.game.visuals.applySkin();this.showSkinScreen(this.returnScreen);this.toast('Default skin restored');return}return oldAction.call(this,a)};
UIP.showTooltip=function(s){oldTooltip.call(this,s);const it=V.Items[s.key];if(this.tooltip&&it){if(it.enchantments)this.tooltip.innerHTML+=it.enchantments.map(e=>`<br><span style="color:#82e8ff">${V.escapeHtml(e)}</span>`).join('');if(it.description)this.tooltip.innerHTML+=`<br><span class="tooltip-key">${V.escapeHtml(it.description)}</span>`}};
UIP.renderWorldInfo=function(){oldInfo.call(this);const dd=this.q('#worldInfo');if(dd)dd.innerHTML=dd.innerHTML.replace('Emberdeep','The Nether').replace('Starreach','The End')};

})();
