(function(){
  'use strict';
  const V=window.Voidlands;
  class AudioSystem{
    constructor(settings){this.settings=settings;this.ctx=null;this.master=null;this.musicGain=null;this.fxGain=null;this.musicTimer=0;this.stepPhase=0;this.started=false;}
    init(){if(this.ctx)return;const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;this.ctx=new AC();this.master=this.ctx.createGain();this.musicGain=this.ctx.createGain();this.fxGain=this.ctx.createGain();this.musicGain.connect(this.master);this.fxGain.connect(this.master);this.master.connect(this.ctx.destination);this.applySettings();this.started=true;}
    resume(){this.init();if(this.ctx&&this.ctx.state==='suspended')this.ctx.resume();}
    applySettings(){if(!this.ctx)return;this.master.gain.value=this.settings.masterVolume;this.musicGain.gain.value=this.settings.musicVolume;this.fxGain.gain.value=this.settings.effectsVolume;}
    tone(freq=.5,dur=.08,type='square',vol=.12,when=0,detune=0){if(!this.ctx)return;const t=this.ctx.currentTime+when,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.value=freq;o.detune.value=detune;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(vol,t+.008);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g);g.connect(this.fxGain);o.start(t);o.stop(t+dur+.02);}
    noise(dur=.08,vol=.12,filter=900){if(!this.ctx)return;const len=Math.floor(this.ctx.sampleRate*dur),buf=this.ctx.createBuffer(1,len,this.ctx.sampleRate),arr=buf.getChannelData(0);for(let i=0;i<len;i++)arr[i]=(Math.random()*2-1)*(1-i/len);const src=this.ctx.createBufferSource(),f=this.ctx.createBiquadFilter(),g=this.ctx.createGain();src.buffer=buf;f.type='lowpass';f.frequency.value=filter;g.gain.value=vol;src.connect(f);f.connect(g);g.connect(this.fxGain);src.start();}
    play(name,surface){this.resume();switch(name){case'menu':this.tone(420,.05,'square',.08);this.tone(620,.05,'square',.06,.045);break;case'break':this.noise(.13,.16,surface==='glass'?2800:800);this.tone(95,.12,'square',.05);break;case'swing':this.noise(.035,.045,1800);this.tone(150,.045,'triangle',.025);break;case'place':this.noise(.06,.11,700);this.tone(120,.07,'square',.04);break;case'pickup':this.tone(660,.05,'square',.07);this.tone(900,.08,'square',.07,.05);break;case'damage':this.noise(.11,.18,400);this.tone(90,.18,'sawtooth',.12);break;case'splash':this.noise(.22,.12,1200);break;case'eat':this.noise(.09,.1,600);this.tone(180,.04,'square',.03);break;case'level':for(let i=0;i<4;i++)this.tone(440*Math.pow(1.26,i),.14,'square',.07,i*.08);break;case'hostile':this.tone(75,.32,'sawtooth',.08);break;case'passive':this.tone(150,.2,'triangle',.07);break;case'door':this.noise(.18,.12,500);break;default:this.tone(240,.05,'square',.05)}}
    footstep(surface='grass'){this.resume();const f={grass:650,dirt:500,stone:900,wood:720,sand:350,gravel:1000,snow:450,water:1200}[surface]||650;this.noise(.055,.07,f);if(surface==='wood')this.tone(175,.04,'square',.025);}
    ambient(time,underwater,weather){if(!this.ctx)return;this.musicTimer-=time;if(this.musicTimer<=0&&this.settings.musicVolume>0){this.musicTimer=12+Math.random()*18;const base=[146.83,174.61,196,220][Math.floor(Math.random()*4)];for(let i=0;i<6;i++){const o=this.ctx.createOscillator(),g=this.ctx.createGain(),t=this.ctx.currentTime+i*1.2;o.type='sine';o.frequency.value=base*Math.pow(2,[0,.25,.5,.75,1,.5][i]/2);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.025,t+.8);g.gain.exponentialRampToValueAtTime(.0001,t+3.5);o.connect(g);g.connect(this.musicGain);o.start(t);o.stop(t+4)}}if(underwater&&Math.random()<time*.2)this.tone(80+Math.random()*70,.5,'sine',.015);if(weather==='rain'&&Math.random()<time*2)this.noise(.06,.01,2500)}
  }
  V.AudioSystem=AudioSystem;
})();
