(function(){
  'use strict';
  const V=window.Voidlands,B=V.B;
  function box(w,h,d,color){const g=new THREE.BoxGeometry(w,h,d),m=new THREE.MeshLambertMaterial({color});const mesh=new THREE.Mesh(g,m);mesh.castShadow=true;mesh.receiveShadow=true;return mesh}
  class Mob{
    constructor(manager,type,x,y,z){this.manager=manager;this.game=manager.game;this.world=this.game.world;this.type=type;this.position=new THREE.Vector3(x,y,z);this.velocity=new THREE.Vector3();this.yaw=Math.random()*Math.PI*2;this.state='wander';this.targetTime=0;this.attackTime=0;this.hurtTime=0;this.age=0;this.grounded=false;this.dead=false;this.width=type==='gloam'?.55:.85;this.height=type==='gloam'?1.8:1.25;this.health=type==='gloam'?18:12;this.maxHealth=this.health;this.speed=type==='gloam'?2.3:1.15;this.attackDamage=type==='gloam'?3:0;this.daylightTimer=0;this.mesh=this.createMesh();this.mesh.position.copy(this.position);manager.group.add(this.mesh)}
    createMesh(){const g=new THREE.Group();g.userData.entity=this;if(this.type==='gloam'){const skin=0x70837a,cloth=0x26394a;const body=box(.5,.7,.28,cloth);body.position.y=1.05;g.add(body);const head=box(.48,.48,.48,skin);head.position.y=1.62;g.add(head);for(const sx of [-1,1]){const arm=box(.18,.72,.18,skin);arm.position.set(sx*.36,1.05,-.12);arm.rotation.x=-.7;g.add(arm);const leg=box(.2,.72,.22,0x1b2732);leg.position.set(sx*.14,.36,0);g.add(leg)}const eyeMat=new THREE.MeshBasicMaterial({color:0x7fffd1});for(const sx of [-1,1]){const e=new THREE.Mesh(new THREE.BoxGeometry(.08,.08,.03),eyeMat);e.position.set(sx*.11,1.68,-.255);g.add(e)}}else{const moss=this.type==='grazer',body=box(.9,.72,.5,moss?0x6b7752:0xb6755d);body.position.y=.82;g.add(body);const head=box(.46,.48,.46,moss?0x829061:0xc58d72);head.position.set(0,1.18,-.43);g.add(head);for(const sx of [-1,1])for(const z of [-.17,.18]){const leg=box(.15,.55,.15,moss?0x394530:0x684638);leg.position.set(sx*.31,.3,z);g.add(leg)}if(moss){for(const sx of [-1,1]){const horn=box(.09,.22,.09,0xd4c9a4);horn.position.set(sx*.2,1.5,-.42);horn.rotation.z=sx*.4;g.add(horn)}}}return g}
    aabb(){return{minX:this.position.x-this.width/2,maxX:this.position.x+this.width/2,minY:this.position.y,maxY:this.position.y+this.height,minZ:this.position.z-this.width/2,maxZ:this.position.z+this.width/2}}
    intersects(a,b){return a.maxX>b.minX&&a.minX<b.maxX&&a.maxY>b.minY&&a.minY<b.maxY&&a.maxZ>b.minZ&&a.minZ<b.maxZ}
    moveAxis(axis,d){if(!d)return false;let blocked=false;const steps=Math.max(1,Math.ceil(Math.abs(d)/.2));for(let s=0;s<steps;s++){const p=d/steps;this.position[axis]+=p;const a=this.aabb();outer:for(let y=Math.floor(a.minY);y<=Math.floor(a.maxY);y++)for(let z=Math.floor(a.minZ);z<=Math.floor(a.maxZ);z++)for(let x=Math.floor(a.minX);x<=Math.floor(a.maxX);x++)for(const b of this.world.collisionBoxes(x,y,z))if(this.intersects(a,b)){blocked=true;if(axis==='x')this.position.x=p>0?b.minX-this.width/2:b.maxX+this.width/2;if(axis==='z')this.position.z=p>0?b.minZ-this.width/2:b.maxZ+this.width/2;if(axis==='y'){if(p>0)this.position.y=b.minY-this.height;else{this.position.y=b.maxY;this.grounded=true}this.velocity.y=0}break outer}if(blocked&&axis!=='y')break}return blocked}
    chooseDirection(){this.targetTime=2+Math.random()*5;this.yaw+=(-1+Math.random()*2)*1.8;this.state=Math.random()<.22?'idle':'wander'}
    update(dt){if(this.dead)return;this.age+=dt;this.hurtTime=Math.max(0,this.hurtTime-dt);this.attackTime=Math.max(0,this.attackTime-dt);const player=this.game.player,dist=this.position.distanceTo(player.position);if(this.type==='gloam'&&!this.game.isNight()){this.daylightTimer+=dt;if(this.daylightTimer>1){this.daylightTimer=0;if(this.world.canSeeSky(this.position.x,this.position.y+this.height,this.position.z))this.takeDamage(2)}}else this.daylightTimer=0;if(dist>70){this.remove();return}if(this.type==='gloam'&&!player.dead&&dist<22){this.state='chase';const dx=player.position.x-this.position.x,dz=player.position.z-this.position.z;this.yaw=Math.atan2(-dx,-dz);if(dist<1.45&&this.attackTime<=0){this.attackTime=1.2;player.damage(this.attackDamage,'was consumed by a gloam');const push=new THREE.Vector3(dx,0,dz).normalize();player.velocity.addScaledVector(push,5);this.game.audio.play('hostile')}}else{this.targetTime-=dt;if(this.targetTime<=0)this.chooseDirection()}
      let speed=this.state==='chase'?this.speed: this.state==='wander'?this.speed*.52:0;const dx=-Math.sin(this.yaw)*speed,dz=-Math.cos(this.yaw)*speed;this.velocity.x=V.lerp(this.velocity.x,dx,dt*4);this.velocity.z=V.lerp(this.velocity.z,dz,dt*4);this.velocity.y-=18*dt;const wasGrounded=this.grounded;this.grounded=false;const bx=this.moveAxis('x',this.velocity.x*dt),bz=this.moveAxis('z',this.velocity.z*dt);if((bx||bz)&&wasGrounded){this.velocity.y=6;this.yaw+=Math.PI*(.4+Math.random()*.7)}this.moveAxis('y',this.velocity.y*dt);if(this.position.y<-5){this.remove();return}
      this.mesh.position.copy(this.position);this.mesh.rotation.y=this.yaw;const bob=Math.sin(this.age*8)*.025;this.mesh.position.y+=bob;this.mesh.traverse(o=>{if(o.material&&o.material.emissive)o.material.emissive.setHex(this.hurtTime>0?0x551111:0)});
    }
    takeDamage(n,knock){if(this.dead)return false;this.health-=n;this.hurtTime=.25;if(knock){this.velocity.addScaledVector(knock,5);this.velocity.y=Math.max(this.velocity.y,2.2)}this.game.audio.play(this.type==='gloam'?'hostile':'passive');if(this.health<=0)this.die();return true}
    die(){this.dead=true;this.game.world.data.stats.mobsDefeated++;const drops=this.type==='gloam'?[V.makeStack('coal',1)]:this.type==='grazer'?[V.makeStack('raw_meat',1+Math.floor(Math.random()*2)),V.makeStack('hide',1)]:[V.makeStack('sun_berry',1+Math.floor(Math.random()*2)),V.makeStack('wool',1+Math.floor(Math.random()*2))];for(const s of drops)this.manager.drop(s,this.position.x,this.position.y+.5,this.position.z);this.game.player.xp+=this.type==='gloam'?5:2;this.remove()}
    remove(){this.dead=true;this.manager.group.remove(this.mesh);this.manager.mobs=this.manager.mobs.filter(m=>m!==this)}
  }
  class DroppedItem{
    constructor(manager,stack,x,y,z){this.manager=manager;this.game=manager.game;this.world=this.game.world;this.stack=V.stackClone(stack);this.position=new THREE.Vector3(x,y,z);this.velocity=new THREE.Vector3((Math.random()-.5)*2.4,2.4+Math.random()*1.8,(Math.random()-.5)*2.4);this.age=0;this.pickupDelay=.45;const tex=V.createItemTexture(this.stack.key,32),it=V.Items[this.stack.key],isBlock=it&&it.blockId!=null&&!V.Blocks[it.blockId].fluid,geo=isBlock?new THREE.BoxGeometry(.25,.25,.25):new THREE.PlaneGeometry(.32,.32),mat=new THREE.MeshBasicMaterial({map:tex,transparent:!isBlock,alphaTest:!isBlock?.08:0,side:THREE.DoubleSide});this.mesh=new THREE.Mesh(geo,mat);this.mesh.castShadow=true;this.mesh.userData.entity=this;this.mesh.position.copy(this.position);manager.group.add(this.mesh)}
    update(dt){this.age+=dt;this.pickupDelay-=dt;if(this.age>300){this.remove();return}const playerCenter=this.game.player.position.clone();playerCenter.y+=.85;const toPlayer=playerCenter.clone().sub(this.position),pickupDistance=toPlayer.distanceTo(new THREE.Vector3(0,0,0));if(this.pickupDelay<=0&&pickupDistance<4.25){const pull=toPlayer.normalize();this.velocity.x+=pull.x*18*dt;this.velocity.y+=pull.y*14*dt;this.velocity.z+=pull.z*18*dt}this.velocity.y-=14*dt;const nx=this.position.x+this.velocity.x*dt,nz=this.position.z+this.velocity.z*dt,ny=this.position.y+this.velocity.y*dt;if(!this.world.isSolid(nx,this.position.y,nz)){this.position.x=nx;this.position.z=nz}else{this.velocity.x*=-.25;this.velocity.z*=-.25}if(!this.world.isSolid(this.position.x,ny,this.position.z))this.position.y=ny;else{if(this.velocity.y<0)this.position.y=Math.ceil(ny);this.velocity.y*=-.18;this.velocity.x*=.78;this.velocity.z*=.78}this.mesh.position.copy(this.position);this.mesh.position.y+=.15+Math.sin(this.age*3)*.08;this.mesh.rotation.y=this.age*1.7;if(this.pickupDelay<=0&&this.position.distanceTo(playerCenter)<1.35){const before=this.stack.count,result=this.game.inventory.insert(this.stack);if(result.inserted>0){this.game.audio.play('pickup');this.game.ui.toast(`${V.Items[this.stack.key].name} ×${result.inserted}`);if(result.remaining)this.stack=result.remaining;else{this.remove();return}this.pickupDelay=.25}if(before===this.stack.count)this.velocity.addScaledVector(toPlayer,-2)}}
    remove(){this.manager.group.remove(this.mesh);this.mesh.geometry.dispose();this.mesh.material.dispose();this.manager.drops=this.manager.drops.filter(d=>d!==this)}
  }
  class EntityManager{
    constructor(game){this.game=game;this.group=new THREE.Group();game.scene.add(this.group);this.mobs=[];this.drops=[];this.spawnTimer=3;}
    destroy(){for(const m of [...this.mobs])m.remove();for(const d of [...this.drops])d.remove();this.game.scene.remove(this.group)}
    drop(stack,x,y,z){if(stack)this.drops.push(new DroppedItem(this,stack,x,y,z))}
    spawn(type,x,y,z){const m=new Mob(this,type,x,y,z);this.mobs.push(m);return m}
    trySpawn(){const p=this.game.player,night=this.game.isNight(),difficulty=this.game.difficulty;if(this.mobs.length>24)return;const angle=Math.random()*Math.PI*2,dist=18+Math.random()*24,x=Math.floor(p.position.x+Math.cos(angle)*dist),z=Math.floor(p.position.z+Math.sin(angle)*dist),y=this.game.world.getSurfaceY(x,z),biome=this.game.world.getBiomeAt(x,z);if(y<2||y>V.WORLD_HEIGHT-3||biome==='ocean')return;if(this.game.world.getBlock(x,y,z)!==B.AIR||this.game.world.getBlock(x,y+1,z)!==B.AIR)return;if(night&&difficulty!=='peaceful'){const hostile=this.mobs.filter(m=>m.type==='gloam').length;if(hostile<10)this.spawn('gloam',x+.5,y,z+.5)}else{const passive=this.mobs.filter(m=>m.type!=='gloam').length;if(passive<12)this.spawn(Math.random()<.55?'grazer':'dunetail',x+.5,y,z+.5)}}
    update(dt){this.spawnTimer-=dt;if(this.spawnTimer<=0){this.spawnTimer=2.5;this.trySpawn()}for(const m of [...this.mobs])m.update(dt);for(const d of [...this.drops])d.update(dt)}
    rayAABB(origin,dir,box,maxDist){let tMin=0,tMax=maxDist;for(const axis of ['x','y','z']){const o=origin[axis],d=dir[axis],min=box['min'+axis.toUpperCase()],max=box['max'+axis.toUpperCase()];if(Math.abs(d)<1e-7){if(o<min||o>max)return null;continue}let t1=(min-o)/d,t2=(max-o)/d;if(t1>t2){const t=t1;t1=t2;t2=t}tMin=Math.max(tMin,t1);tMax=Math.min(tMax,t2);if(tMin>tMax)return null}return tMin<=maxDist?tMin:null}
    attackRay(origin,dir,maxDist,damage){let best=null,bestT=maxDist;for(const m of this.mobs){if(m.dead)continue;const a=m.aabb(),pad=.16,box={minX:a.minX-pad,maxX:a.maxX+pad,minY:a.minY-.08,maxY:a.maxY+pad,minZ:a.minZ-pad,maxZ:a.maxZ+pad},t=this.rayAABB(origin,dir,box,bestT);if(t==null)continue;best=m;bestT=t}if(best){best.takeDamage(damage,dir.clone());return{mob:best,distance:bestT}}return null}
    serialize(){return this.mobs.filter(m=>!m.dead&&m.position.distanceTo(this.game.player.position)<45).map(m=>({type:m.type,x:m.position.x,y:m.position.y,z:m.position.z,health:m.health}))}
    load(list){for(const e of list||[]){const m=this.spawn(e.type,e.x,e.y,e.z);m.health=e.health||m.maxHealth}}
  }
  V.EntityManager=EntityManager;
})();
