(function(){
'use strict';const V=window.Voidlands,B=V.B;
class Game{
 constructor(app,data){this.app=app;this.ui=app.ui;this.storage=app.storage;this.settings=app.settings;this.audio=app.audio;this.data=data;this.mode=data.mode;this.difficulty=data.mode==='hardcore'?'hard':data.difficulty;this.canvas=app.canvas;this.renderer=app.renderer;this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0x78a8c2);this.scene.fog=new THREE.Fog(0x78a8c2,20,this.settings.renderDistance*16*.95);this.camera=new THREE.PerspectiveCamera(this.settings.fov,innerWidth/innerHeight,.05,600);this.keys={};this.mouse={left:false,right:false};this.paused=true;this.state='loading';this.hudHidden=false;this.debug=false;this.breaking=null;this.target=null;this.particles=[];this.acc=0;this.last=performance.now();this.saveTimer=0;this.torchTimer=0;this.weather=data.weather||'clear';this.weatherTime=data.weatherTime||9000;this.handlers=[];this.hudTimer=0;this.inventoryRenderTimer=0;this.wheelAccumulator=0;this.wheelResetTimer=null;this.lastWheelTime=0;this.pointerHintTimer=null;this.attackCooldown=0;
 this.setupLights();this.world=new V.World(this,data);this.inventory=new V.Inventory(data.inventory,this.mode);this.inventory.game=this;this.player=new V.Player(this,data.player);this.entities=new V.EntityManager(this);this.entities.load(data.entities);this.visuals=new V.PlayerVisuals(this);this.createHighlight();this.createWeather();this.bindInput();this.applySettings();}
 setupLights(){
  this.ambient=new THREE.HemisphereLight(0xb9ddff,0x25311f,.82);this.scene.add(this.ambient);
  this.sunLight=new THREE.DirectionalLight(0xfff1c4,1.05);this.sunLight.castShadow=this.settings.shadows;this.sunLight.shadow.mapSize.set(1024,1024);this.sunLight.shadow.camera.left=-48;this.sunLight.shadow.camera.right=48;this.sunLight.shadow.camera.top=48;this.sunLight.shadow.camera.bottom=-48;this.sunLight.shadow.camera.near=.5;this.sunLight.shadow.camera.far=220;this.scene.add(this.sunLight,this.sunLight.target);
  this.sunMesh=new THREE.Mesh(new THREE.SphereGeometry(3,16,12),new THREE.MeshBasicMaterial({color:0xfff1ac,toneMapped:false}));
  this.moonMesh=new THREE.Mesh(new THREE.SphereGeometry(2.3,16,12),new THREE.MeshBasicMaterial({color:0xc9d9ef,toneMapped:false}));
  this.sunGlow=new THREE.Mesh(new THREE.SphereGeometry(5.8,16,12),new THREE.MeshBasicMaterial({color:0xffc85c,transparent:true,opacity:.2,depthWrite:false,blending:THREE.AdditiveBlending,toneMapped:false}));
  this.moonGlow=new THREE.Mesh(new THREE.SphereGeometry(4.1,16,12),new THREE.MeshBasicMaterial({color:0x8eb9ff,transparent:true,opacity:.12,depthWrite:false,blending:THREE.AdditiveBlending,toneMapped:false}));
  this.scene.add(this.sunMesh,this.moonMesh,this.sunGlow,this.moonGlow);
  const skyGeo=new THREE.SphereGeometry(285,28,18),skyColors=new Float32Array(skyGeo.attributes.position.count*3);skyGeo.setAttribute('color',new THREE.BufferAttribute(skyColors,3));this.skyDome=new THREE.Mesh(skyGeo,new THREE.MeshBasicMaterial({vertexColors:true,side:THREE.BackSide,depthWrite:false,depthTest:false,fog:false,toneMapped:false}));this.skyDome.renderOrder=-1000;this.skyDome.visible=false;this.scene.add(this.skyDome);
  const pos=[];const r=V.rng(this.data.seedNumber+1234);for(let i=0;i<900;i++){const a=r()*Math.PI*2,b=Math.acos(r()*2-1),rad=250;pos.push(Math.sin(b)*Math.cos(a)*rad,Math.abs(Math.cos(b))*rad+15,Math.sin(b)*Math.sin(a)*rad)}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));this.stars=new THREE.Points(geo,new THREE.PointsMaterial({color:0xffffff,size:.8,sizeAttenuation:false,transparent:true,depthWrite:false,toneMapped:false}));this.scene.add(this.stars);
  this.cloudGroup=new THREE.Group();this.cloudMaterial=new THREE.MeshBasicMaterial({color:0xffffff,transparent:true,opacity:.58,depthWrite:false,fog:true,toneMapped:false});const cloudGeo=new THREE.BoxGeometry(1,1,1),cr=V.rng(this.data.seedNumber+7731);for(let i=0;i<26;i++){const cloud=new THREE.Group(),parts=3+Math.floor(cr()*4);for(let j=0;j<parts;j++){const m=new THREE.Mesh(cloudGeo,this.cloudMaterial);m.scale.set(4+cr()*7,.45+cr()*.45,2.5+cr()*5);m.position.set(j*4-parts*2+cr()*2,(cr()-.5)*.5,(cr()-.5)*3);cloud.add(m)}cloud.position.set((cr()-.5)*230,50+cr()*14,(cr()-.5)*230);cloud.userData.baseX=cloud.position.x;cloud.userData.baseZ=cloud.position.z;this.cloudGroup.add(cloud)}this.cloudGroup.visible=false;this.scene.add(this.cloudGroup);
  this.torchLights=[];for(let i=0;i<8;i++){const l=new THREE.PointLight(0xffa33a,0,10,2);this.scene.add(l);this.torchLights.push(l)}
}
 createWeather(){const count=700,pos=new Float32Array(count*3);for(let i=0;i<count;i++){pos[i*3]=(Math.random()-.5)*55;pos[i*3+1]=Math.random()*35;pos[i*3+2]=(Math.random()-.5)*55}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(pos,3));this.weatherPoints=new THREE.Points(geo,new THREE.PointsMaterial({color:0xbad9ef,size:.09,transparent:true,opacity:.7}));this.weatherPoints.visible=false;this.scene.add(this.weatherPoints)}
 createHighlight(){const geo=new THREE.EdgesGeometry(new THREE.BoxGeometry(1.006,1.006,1.006));this.highlight=new THREE.LineSegments(geo,new THREE.LineBasicMaterial({color:0x101010,transparent:true,opacity:.8}));this.highlight.visible=false;this.scene.add(this.highlight)}
 async initialize(){const load=document.querySelector('#loadingScreen'),fill=document.querySelector('#loadingFill'),text=document.querySelector('#loadingText'),tips=['Hostile mobs emerge when night falls.','Double-tap Space to fly in Creative mode.','Hold C to zoom.','Use F3 for world and performance details.','Rivers often reveal cave openings.'];load.classList.remove('hidden');document.querySelector('#loadingTip').textContent=tips[Math.floor(Math.random()*tips.length)];const p=this.player.position,cx=V.floorDiv(p.x,V.CHUNK_SIZE),cz=V.floorDiv(p.z,V.CHUNK_SIZE),jobs=[];for(let dz=-2;dz<=2;dz++)for(let dx=-2;dx<=2;dx++)if(dx*dx+dz*dz<=6)jobs.push({cx:cx+dx,cz:cz+dz});jobs.sort((a,b)=>(a.cx-cx)**2+(a.cz-cz)**2-((b.cx-cx)**2+(b.cz-cz)**2));for(let i=0;i<jobs.length;i++){text.textContent=i<jobs.length/2?'Shaping terrain...':'Growing the wilds...';this.world.buildChunk(jobs[i].cx,jobs[i].cz);fill.style.width=((i+1)/jobs.length*100)+'%';await new Promise(r=>requestAnimationFrame(r))}this.player.ensureSafePosition();this.player.updateCamera();load.classList.add('hidden');this.world.queueAround(p.x,p.z,true);this.state='playing';this.resume();this.last=performance.now();this.loop();}
 bindInput(){const on=(target,type,fn,opts)=>{target.addEventListener(type,fn,opts);this.handlers.push(()=>target.removeEventListener(type,fn,opts))};on(document,'keydown',e=>this.keyDown(e),true);on(document,'keyup',e=>this.keyUp(e),true);on(document,'mousemove',e=>{if(document.pointerLockElement===this.canvas&&!this.paused)this.player.look(e.movementX||0,e.movementY||0)});on(this.canvas,'mousedown',e=>this.mouseDown(e));on(document,'mouseup',e=>this.mouseUp(e));on(this.canvas,'wheel',e=>this.handleWheel(e),{passive:false});on(this.canvas,'contextmenu',e=>e.preventDefault());on(this.canvas,'click',()=>{if(this.state==='playing'&&!this.paused)this.requestMouseLock()});on(document,'pointerlockchange',()=>{if(document.pointerLockElement===this.canvas){this.clearInput(true);return}this.clearInput(true);if(this.state==='playing'&&!this.paused)this.pause()});on(window,'blur',()=>{this.clearInput(true);if(this.state==='playing'&&!this.paused)this.pause()});on(document,'visibilitychange',()=>{if(document.hidden){this.clearInput(true);if(this.state==='playing'&&!this.paused)this.pause()}});on(window,'resize',()=>this.resize());on(window,'beforeunload',()=>this.save());}
 bindingCodes(binding){return V.KEY_ALIASES[binding]||[binding]}
 matchesBinding(code,binding){return this.bindingCodes(binding).includes(code)}
 isActionDown(action){const binding=this.settings.keybinds[action];return !!binding&&this.bindingCodes(binding).some(code=>!!this.keys[code])}
 isGameplayCode(code){const bound=Object.values(this.settings.keybinds).some(binding=>this.matchesBinding(code,binding));return bound||/^Digit[1-9]$/.test(code)||code==='Escape'}
 clearInput(resetTaps=true){this.keys={};this.mouse.left=this.mouse.right=false;this.wheelAccumulator=0;clearTimeout(this.wheelResetTimer);this.cancelBreak();if(this.player){this.player.stopEating();this.player.sprinting=false;this.player.velocity.x=0;this.player.velocity.z=0;if(resetTaps){this.player.lastSpace=-Infinity;this.player.lastForward=-Infinity}}}
 requestMouseLock(){if(this.paused||this.state!=='playing'||document.pointerLockElement===this.canvas)return;try{const result=this.canvas.requestPointerLock();if(result&&typeof result.catch==='function')result.catch(()=>this.showPointerHint())}catch(e){this.showPointerHint()}}
 showPointerHint(){clearTimeout(this.pointerHintTimer);this.pointerHintTimer=setTimeout(()=>{if(this.state==='playing'&&!this.paused&&document.pointerLockElement!==this.canvas)this.ui.toast('Click the game view to capture the mouse')},120)}
 handleWheel(e){if(this.state!=='playing'||this.paused)return;e.preventDefault();const now=performance.now(),delta=e.deltaY;if(!delta)return;if(now-this.lastWheelTime<65)return;if(e.deltaMode!==0){this.wheelAccumulator=0;this.lastWheelTime=now;this.inventory.setSelected(this.inventory.selected+(delta>0?1:-1));this.ui.refreshHUD();this.ui.selectedName();return}if(this.wheelAccumulator&&Math.sign(delta)!==Math.sign(this.wheelAccumulator))this.wheelAccumulator=0;this.wheelAccumulator+=delta;clearTimeout(this.wheelResetTimer);this.wheelResetTimer=setTimeout(()=>this.wheelAccumulator=0,140);if(Math.abs(this.wheelAccumulator)<45)return;this.lastWheelTime=now;const direction=this.wheelAccumulator>0?1:-1;this.wheelAccumulator=0;this.inventory.setSelected(this.inventory.selected+direction);this.ui.refreshHUD();this.ui.selectedName()}
 keyDown(e){if(this.state==='destroyed')return;const k=this.settings.keybinds;if(this.isGameplayCode(e.code)&&this.state!=='loading')e.preventDefault();if(this.state==='chat'){if(e.code==='Escape')this.closeChat();return}if(this.state==='inventory'){if(this.matchesBinding(e.code,k.inventory)||e.code==='Escape')this.closeInventory();return}if(this.paused){if(e.code==='Escape'&&this.ui.current==='pauseScreen')this.resume();return}this.keys[e.code]=true;if(e.repeat)return;if(this.matchesBinding(e.code,k.forward))this.player.onForwardPress();if(this.matchesBinding(e.code,k.jump))this.player.onJumpPress();if(this.matchesBinding(e.code,k.inventory))this.openInventory('player');else if(this.matchesBinding(e.code,k.hud)){this.hudHidden=!this.hudHidden;document.querySelector('#hud').classList.toggle('hidden',this.hudHidden)}else if(this.matchesBinding(e.code,k.debug)){this.debug=!this.debug;document.querySelector('#debugOverlay').classList.toggle('hidden',!this.debug)}else if(this.matchesBinding(e.code,k.perspective))this.player.cyclePerspective();else if(this.matchesBinding(e.code,k.chat))this.openChat();else if(this.matchesBinding(e.code,k.drop))this.dropSelected();else if(/^Digit[1-9]$/.test(e.code)){this.inventory.setSelected(Number(e.code.slice(5))-1);this.ui.refreshHUD();this.ui.selectedName()}else if(e.code==='Escape')this.pause()}
 keyUp(e){if(this.isGameplayCode(e.code)&&this.state!=='loading')e.preventDefault();this.keys[e.code]=false}
 mouseDown(e){if(this.paused||this.state!=='playing')return;this.audio.resume();if(document.pointerLockElement!==this.canvas){this.requestMouseLock();return}if(e.button===0){this.mouse.left=true;this.beginBreak()}if(e.button===2){this.mouse.right=true;this.useOrPlace()}if(e.button===1){e.preventDefault();this.pickBlock()}}
 mouseUp(e){if(e.button===0){this.mouse.left=false;this.cancelBreak()}if(e.button===2){this.mouse.right=false;this.player.stopEating()}}
 resize(){this.renderer.setSize(innerWidth,innerHeight,false);this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();if(this.viewCamera){this.viewCamera.aspect=innerWidth/innerHeight;this.viewCamera.updateProjectionMatrix()}}
 applySettings(){const vibrant=!!this.settings.vibrantVisuals;this.camera.fov=this.settings.fov;this.camera.updateProjectionMatrix();if(this.viewCamera){this.viewCamera.fov=V.clamp(this.settings.fov*.92,58,82);this.viewCamera.aspect=innerWidth/innerHeight;this.viewCamera.updateProjectionMatrix()}this.renderer.shadowMap.enabled=this.settings.shadows;this.renderer.shadowMap.type=vibrant?THREE.PCFSoftShadowMap:(this.settings.graphics==='fast'?THREE.BasicShadowMap:THREE.PCFSoftShadowMap);this.renderer.setPixelRatio(Math.min(devicePixelRatio,this.settings.graphics==='fast'?1:this.settings.graphics==='ultra'?2:1.5));this.renderer.toneMapping=vibrant?THREE.ACESFilmicToneMapping:THREE.NoToneMapping;this.renderer.toneMappingExposure=vibrant?1.08:1;this.canvas.classList.toggle('vibrant-visuals',vibrant);this.scene.fog.near=vibrant?Math.max(14,this.settings.renderDistance*3):20;this.scene.fog.far=this.settings.renderDistance*16*(vibrant?1.08:.95);this.sunLight.shadow.mapSize.set(vibrant&&this.settings.graphics==='ultra'?2048:1024,vibrant&&this.settings.graphics==='ultra'?2048:1024);this.sunLight.castShadow=this.settings.shadows;if(this.skyDome)this.skyDome.visible=vibrant;if(this.cloudGroup)this.cloudGroup.visible=vibrant;if(this.sunGlow)this.sunGlow.visible=vibrant;if(this.moonGlow)this.moonGlow.visible=vibrant;if(this.world){this.world.setVibrant(vibrant);this.world.maxBuildPerFrame=this.settings.graphics==='ultra'?2:1;this.world.queueAround(this.player.position.x,this.player.position.z,true)}this.audio.settings=this.settings;this.audio.applySettings()}
 pause(){if(this.player.dead)return;this.paused=true;this.state='paused';this.clearInput(true);if(document.pointerLockElement)document.exitPointerLock();this.ui.show('pauseScreen')}
 resume(){this.clearInput(true);this.paused=false;this.state='playing';this.ui.qa('.screen').forEach(x=>x.classList.remove('active'));document.querySelector('#hud').classList.toggle('hidden',this.hudHidden);this.ui.refreshHUD();this.canvas.focus();this.requestMouseLock();this.showPointerHint()}
 openInventory(type,data){this.clearInput(true);this.paused=true;this.state='inventory';this.inventory.open(type,data);if(document.pointerLockElement)document.exitPointerLock();this.ui.showInventory()}
 closeInventory(){this.inventory.close();this.ui.refreshHUD();this.resume()}
 openChat(){this.clearInput(true);this.paused=true;this.state='chat';if(document.pointerLockElement)document.exitPointerLock();const box=document.querySelector('#chatBox'),input=document.querySelector('#chatInput');box.classList.remove('hidden');input.value='';input.focus();input.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();const v=input.value.trim();if(v)this.handleChat(v);this.closeChat()}else if(e.key==='Escape'){e.preventDefault();this.closeChat()}}}
 closeChat(){document.querySelector('#chatBox').classList.add('hidden');this.resume()}
 handleChat(v){if(v[0]!=='/'){this.ui.chat(`<You> ${v}`);return}const p=v.slice(1).split(/\s+/),cmd=p.shift().toLowerCase();if(cmd==='help')this.ui.chat('Commands: /seed /time /weather /gamemode /tp /give /dimension /kill');else if(cmd==='seed')this.ui.chat(`Seed: ${this.data.seed}`);else if(cmd==='time'){if(p[0]==='set'){const t={day:1000,noon:6000,night:13000,midnight:18000}[p[1]];this.data.time=t==null?Number(p[1])||this.data.time:t}this.ui.chat(`Time: ${Math.floor(this.data.time)}`)}else if(cmd==='weather'){if(['clear','rain','snow'].includes(p[0])){this.weather=p[0];this.weatherTime=6000;this.ui.chat(`Weather set to ${p[0]}`)}}else if(cmd==='gamemode'){if(['creative','survival'].includes(p[0])){this.mode=p[0];this.data.mode=p[0];if(p[0]!=='creative')this.player.flying=false;this.ui.chat(`Game mode: ${p[0]}`)}}else if(cmd==='tp'&&p.length>=3){this.player.position.set(Number(p[0]),Number(p[1]),Number(p[2]));this.player.velocity.set(0,0,0);this.ui.chat('Teleported')}else if(cmd==='give'){const key=p[0],n=V.clamp(Number(p[1])||1,1,640);if(V.Items[key]){this.inventory.add(V.makeStack(key,n));this.ui.chat(`Given ${V.Items[key].name} ×${n}`)}else this.ui.chat('Unknown item key')}else if(cmd==='kill')this.player.damage(999,'used /kill');else this.ui.chat('Unknown command. Use /help.')}
 dropSelected(){const s=this.inventory.selectedStack();if(!s)return;const one=V.stackClone(s);one.count=1;s.count--;if(s.count<=0)this.inventory.slots[this.inventory.selected]=null;const pos=this.player.eyePosition().addScaledVector(this.player.viewDirection(),.8);this.entities.drop(one,pos.x,pos.y,pos.z);const d=this.entities.drops[this.entities.drops.length-1];d.velocity.copy(this.player.viewDirection()).multiplyScalar(5);d.pickupDelay=1.2;this.ui.refreshHUD()}
 targetUpdate(){this.target=this.world.raycast(this.player.eyePosition(),this.player.viewDirection(),this.mode==='creative'?8:5.2);this.highlight.visible=!!this.target;if(this.target)this.highlight.position.set(this.target.x+.5,this.target.y+.5,this.target.z+.5)}
 beginBreak(){const dir=this.player.viewDirection(),origin=this.player.eyePosition(),item=this.inventory.selectedStack(),it=item&&V.Items[item.key],damage=this.mode==='creative'?999:(it&&it.damage)||1,reach=this.mode==='creative'?6:4.5,blockHit=this.world.raycast(origin,dir,reach),entityReach=blockHit?Math.min(reach,Math.max(0,blockHit.distance-.03)):reach;this.visuals.swing('attack');this.audio.play('swing');if(this.attackCooldown<=0){const hit=this.entities.attackRay(origin,dir,entityReach,damage);if(hit){this.attackCooldown=.24;if(item&&it&&it.durability&&this.mode!=='creative')this.inventory.damageSelected(1);this.ui.refreshHUD();return}}const target=blockHit||this.target;if(!target)return;const d=V.Blocks[target.id];if(!d||d.hardness>=999999)return;if(this.mode==='creative'){this.finishBreak(target);return}this.breaking={key:V.blockKey(target.x,target.y,target.z),target:Object.assign({},target),progress:0};document.querySelector('#breakProgress').classList.remove('hidden')}
 cancelBreak(){this.breaking=null;document.querySelector('#breakProgress').classList.add('hidden')}
 breakSpeed(d){const s=this.inventory.selectedStack(),it=s&&V.Items[s.key];let speed=.7;if(it&&it.tool===d.tool)speed=it.speed||1;else if(d.tool!=='any')speed=.22;else if(it&&it.tool==='shovel'&&['dirt','sand','gravel','snow'].includes(d.key))speed=it.speed;return speed/d.hardness}
 finishBreak(t){const id=this.world.getBlock(t.x,t.y,t.z),d=V.Blocks[id];if(id===B.AIR||!d)return;const s=this.inventory.selectedStack(),it=s&&V.Items[s.key],canHarvest=!d.requiresTool||!!(it&&it.tool===d.tool&&(it.tier||0)>=(d.minTier||0));this.world.setBlock(t.x,t.y,t.z,B.AIR);this.audio.play('break',d.sound);this.spawnParticles(t.x+.5,t.y+.5,t.z+.5,id);if(this.mode!=='creative'){if(d.drop&&canHarvest){this.entities.drop(V.makeStack(d.drop,1),t.x+.5,t.y+.55,t.z+.5);const drop=this.entities.drops[this.entities.drops.length-1];if(drop)drop.pickupDelay=.18}else if(d.drop&&d.requiresTool)this.ui.toast(`Use a tier ${d.minTier||1}+ ${d.tool} to collect ${d.name}`);if(it&&it.durability)this.inventory.damageSelected(1)}this.cancelBreak();this.ui.refreshHUD()}
 useOrPlace(){this.visuals.swing('use');const s=this.inventory.selectedStack(),it=s&&V.Items[s.key];if(it&&it.food&&this.player.startEating())return;if(this.target){const id=this.world.getBlock(this.target.x,this.target.y,this.target.z),d=V.Blocks[id];if(id===B.DOOR){this.world.toggleDoor(this.target.x,this.target.y,this.target.z);this.audio.play('door');return}if(id===B.BED){this.useBed(this.target.x,this.target.y,this.target.z);return}if(d&&d.interact){const e=this.world.ensureBlockEntity(this.target.x,this.target.y,this.target.z,d.interact);this.openInventory(d.interact,e);return}}
 if(!this.target||!s||!it||it.blockId==null)return;const p=this.target.place;if(p.y<=0||p.y>=V.WORLD_HEIGHT)return;const bd=V.Blocks[it.blockId];if(!bd)return;const pa=this.player.aabbAt(this.player.position),ba={minX:p.x,minY:p.y,minZ:p.z,maxX:p.x+1,maxY:p.y+1,maxZ:p.z+1};if(bd.solid&&this.player.intersects(pa,ba)){this.ui.toast('Cannot place a block inside yourself');return}const existing=this.world.getBlock(p.x,p.y,p.z);if(existing!==B.AIR&&existing!==B.WATER&&existing!==B.TALL_GRASS&&existing!==B.RED_FLOWER&&existing!==B.GOLD_FLOWER)return;if(this.world.setBlock(p.x,p.y,p.z,it.blockId)){if(it.blockId===B.CHEST)this.world.ensureBlockEntity(p.x,p.y,p.z,'chest');if(it.blockId===B.FURNACE)this.world.ensureBlockEntity(p.x,p.y,p.z,'furnace');if(it.blockId===B.DOOR)this.world.ensureBlockEntity(p.x,p.y,p.z,'door');if(it.blockId===B.BED)this.world.ensureBlockEntity(p.x,p.y,p.z,'bed');this.audio.play('place',bd.sound);if(this.mode!=='creative'){s.count--;if(s.count<=0)this.inventory.slots[this.inventory.selected]=null}this.ui.refreshHUD()}}
 useBed(x,y,z){const spawn={x:x+.5,y:y+.58,z:z+.5};this.data.spawn=spawn;this.player.spawn=spawn;const nearby=this.entities.mobs.some(m=>!m.dead&&m.type==='gloam'&&m.position.distanceTo(this.player.position)<8);if(!this.isNight()){this.ui.toast('Respawn point set. Beds can skip only the night.');this.save();return}if(nearby){this.ui.toast('The gloam is too close to sleep. Respawn point set.');this.save();return}this.data.time=1000;this.weather='clear';this.weatherTime=9000;for(const m of [...this.entities.mobs])if(m.type==='gloam'&&m.position.distanceTo(this.player.position)<28)m.remove();const fade=document.querySelector('#sleepFade');if(fade){fade.classList.add('active');setTimeout(()=>fade.classList.remove('active'),900)}this.audio.play('menu');this.ui.chat('You slept until dawn. Respawn point set.');this.save()}
  pickBlock(){if(this.mode!=='creative'||!this.target)return;const key=V.Blocks[this.target.id].key;let i=this.inventory.slots.findIndex((s,j)=>j<9&&s&&s.key===key);if(i<0){i=this.inventory.selected;this.inventory.slots[i]=V.makeStack(key,64)}this.inventory.setSelected(i);this.ui.refreshHUD();this.ui.selectedName()}
 spawnParticles(x,y,z,id){const col=new THREE.Color(V.hashString(V.Blocks[id].key)&0xffffff);for(let i=0;i<12;i++){const m=new THREE.Mesh(new THREE.BoxGeometry(.08,.08,.08),new THREE.MeshBasicMaterial({color:col}));m.position.set(x+(Math.random()-.5)*.6,y+(Math.random()-.5)*.6,z+(Math.random()-.5)*.6);this.scene.add(m);this.particles.push({mesh:m,v:new THREE.Vector3((Math.random()-.5)*3,Math.random()*3,(Math.random()-.5)*3),life:.5+Math.random()*.4})}}
 updateParticles(dt){for(let i=this.particles.length-1;i>=0;i--){const p=this.particles[i];p.life-=dt;p.v.y-=8*dt;p.mesh.position.addScaledVector(p.v,dt);p.mesh.scale.multiplyScalar(.97);if(p.life<=0){this.scene.remove(p.mesh);p.mesh.geometry.dispose();p.mesh.material.dispose();this.particles.splice(i,1)}}}
 updateAtmosphere(dt){
  this.data.time=(this.data.time+dt*20)%24000;const a=(this.data.time/24000)*Math.PI*2,sunY=Math.sin(a),sunX=Math.cos(a),day=V.clamp((sunY+.25)/.75,0,1),twilight=V.clamp(1-Math.abs(sunY)/.32,0,1);const p=this.player.position,vibrant=!!this.settings.vibrantVisuals;
  this.sunLight.position.set(p.x+sunX*70,p.y+sunY*80,p.z+25);this.sunLight.target.position.set(p.x,p.y,p.z);this.sunMesh.position.set(p.x+sunX*180,p.y+sunY*180,p.z+50);this.moonMesh.position.set(p.x-sunX*180,p.y-sunY*180,p.z-50);this.sunGlow.position.copy(this.sunMesh.position);this.moonGlow.position.copy(this.moonMesh.position);this.sunMesh.visible=sunY>-.15;this.sunGlow.visible=vibrant&&sunY>-.15;this.moonMesh.visible=sunY<.25;this.moonGlow.visible=vibrant&&sunY<.25;
  this.sunLight.intensity=vibrant?Math.max(.025,day*1.55):Math.max(.03,day*1.2);this.ambient.intensity=vibrant?.2+day*.9:.14+day*.72;this.sunLight.color.set(vibrant?0xfff5d9:0xfff1c4);if(vibrant&&twilight>.05)this.sunLight.color.lerp(new THREE.Color(0xffa35c),twilight*.68);this.ambient.color.set(vibrant?0xaedbff:0xb9ddff);this.ambient.groundColor.set(vibrant?0x3d4d31:0x25311f);
  let sky,horizon;if(vibrant){sky=new THREE.Color(0x050b1c).lerp(new THREE.Color(0x3e92e6),day);horizon=new THREE.Color(0x112245).lerp(new THREE.Color(0xa8ddff),day);if(twilight>.02){sky.lerp(new THREE.Color(0x7a4f84),twilight*.34);horizon.lerp(new THREE.Color(0xff895e),twilight*.72)}if(this.weather!=='clear'){sky.lerp(new THREE.Color(0x415a70),.52);horizon.lerp(new THREE.Color(0x6d8291),.55)}this.scene.background.copy(horizon);this.scene.fog.color.copy(horizon);this.skyDome.position.copy(p);const pa=this.skyDome.geometry.attributes.position.array,ca=this.skyDome.geometry.attributes.color.array;for(let i=0;i<pa.length;i+=3){const t=V.clamp((pa[i+1]/285+.08)/.85,0,1),c=horizon.clone().lerp(sky,t);ca[i]=c.r;ca[i+1]=c.g;ca[i+2]=c.b}this.skyDome.geometry.attributes.color.needsUpdate=true;this.cloudGroup.position.set(p.x+(performance.now()*.0008)%35,0,p.z);this.cloudMaterial.opacity=(this.weather==='clear'?.56:.76)*(.55+day*.45);this.cloudMaterial.color.set(this.weather==='clear'?0xffffff:0xaebcc6);this.sunGlow.material.opacity=.12+day*.2;this.moonGlow.material.opacity=.08+(1-day)*.12;this.sunMesh.material.color.set(0xfff2b2);this.moonMesh.material.color.set(0xd9e7ff);this.world.materials.fluid.opacity=.72+Math.sin(performance.now()*.0017)*.055;this.world.materials.fluid.color.set(day>.25?0xaedfff:0x6f9fc8)}else{sky=new THREE.Color().setRGB(V.lerp(.025,.45,day),V.lerp(.04,.66,day),V.lerp(.08,.78,day));if(Math.abs(sunY)<.25)sky.lerp(new THREE.Color(0xca6e57),.35);if(this.weather!=='clear')sky.lerp(new THREE.Color(0x5f7180),.45);this.scene.background.copy(sky);this.scene.fog.color.copy(sky);this.world.materials.fluid.color.set(0xffffff)}
  this.stars.material.opacity=(1-day)*(vibrant?.95:1);this.stars.position.set(p.x,0,p.z);this.weatherTime-=dt*20;if(this.weatherTime<=0){const r=Math.random();this.weather=r<.65?'clear':this.world.getBiomeAt(p.x,p.z)==='frostlands'?'snow':'rain';this.weatherTime=4000+Math.random()*12000}this.weatherPoints.visible=this.weather!=='clear';if(this.weatherPoints.visible){this.weatherPoints.position.set(p.x,p.y,p.z);const arr=this.weatherPoints.geometry.attributes.position.array;for(let i=0;i<arr.length;i+=3){arr[i+1]-=dt*(this.weather==='snow'?3:18);if(arr[i+1]<-5)arr[i+1]=35}this.weatherPoints.geometry.attributes.position.needsUpdate=true;this.weatherPoints.material.color.set(this.weather==='snow'?0xffffff:0xa8c9dc);this.weatherPoints.material.size=this.weather==='snow'?.16:.07}document.querySelector('#weatherLabel').textContent=`${this.weather==='clear'?'':this.weather.toUpperCase()+' · '}${V.formatTime(this.data.time)}`
}
 updateTorches(dt){this.torchTimer-=dt;if(this.torchTimer>0)return;this.torchTimer=.6;const vibrant=!!this.settings.vibrantVisuals,ts=this.world.nearbyTorches(this.player.position.x,this.player.position.y,this.player.position.z,vibrant?12:10);this.torchLights.forEach((l,i)=>{if(ts[i]){l.position.set(ts[i].x,ts[i].y,ts[i].z);l.color.set(vibrant?0xff9d42:0xffa33a);l.distance=vibrant?13:10;l.intensity=vibrant?1.85:1.25}else l.intensity=0})}
 debugUpdate(fps){if(!this.debug)return;const p=this.player.position,cx=V.floorDiv(p.x,V.CHUNK_SIZE),cz=V.floorDiv(p.z,V.CHUNK_SIZE),b=this.world.getBiomeAt(p.x,p.z);document.querySelector('#debugOverlay').textContent=`Voidlands ${V.VERSION}\n${fps.toFixed(0)} fps · ${this.renderer.info.render.calls} draw calls\nXYZ ${p.x.toFixed(2)} / ${p.y.toFixed(2)} / ${p.z.toFixed(2)}\nChunk ${cx}, ${cz} · ${this.world.chunkMeshes.size} loaded\nFacing ${((this.player.yaw*180/Math.PI)%360+360).toFixed(0)}°\nBiome ${b} · ${this.world.dimension}\nSeed ${this.data.seed}\nMode ${this.mode}${this.player.flying?' · Flying':''}\nEntities ${this.entities.mobs.length} mobs / ${this.entities.drops.length} items`}
 renderFrame(){this.renderer.autoClear=true;this.renderer.render(this.scene,this.camera);if(this.viewScene&&this.viewCamera&&this.visuals&&this.visuals.firstPerson.visible){this.renderer.autoClear=false;this.renderer.clearDepth();this.renderer.render(this.viewScene,this.viewCamera);this.renderer.autoClear=true}}
 loop(){if(this.state==='destroyed')return;requestAnimationFrame(()=>this.loop());const now=performance.now(),raw=Math.min(.1,(now-this.last)/1000);this.last=now;this.fps=V.lerp(this.fps||60,1/Math.max(raw,.001),.08);if(!this.paused){this.acc+=raw;let steps=0;while(this.acc>=1/60&&steps++<6){this.fixedUpdate(1/60);this.acc-=1/60}this.renderUpdate(raw)}else if(this.state==='inventory'){this.world.tickFurnaces(raw);this.inventoryRenderTimer-=raw;if(this.inventoryRenderTimer<=0){this.inventoryRenderTimer=.25;this.ui.renderInventory()}}this.renderFrame()}
 fixedUpdate(dt){this.player.update(dt);this.player.updateEating(dt);this.entities.update(dt);this.world.tickFurnaces(dt);this.data.stats.playTime+=dt;this.saveTimer+=dt;if(this.saveTimer>20){this.saveTimer=0;this.save()}this.world.queueAround(this.player.position.x,this.player.position.z)}
 renderUpdate(dt){this.attackCooldown=Math.max(0,this.attackCooldown-dt);this.world.updateBuilds();this.targetUpdate();if(this.visuals)this.visuals.update(dt);this.world.materials.fluid.opacity=.66+Math.sin(performance.now()*.0017)*.06;if(this.breaking){if(!this.mouse.left||!this.target||V.blockKey(this.target.x,this.target.y,this.target.z)!==this.breaking.key)this.cancelBreak();else{const d=V.Blocks[this.target.id];this.breaking.progress+=this.breakSpeed(d)*dt;document.querySelector('#breakProgress div').style.width=Math.min(100,this.breaking.progress*100)+'%';if(this.breaking.progress>=1)this.finishBreak(this.target)}}this.updateParticles(dt);this.updateAtmosphere(dt);this.updateTorches(dt);this.audio.ambient(dt,this.player.headWater,this.weather);const zoom=this.isActionDown('zoom');document.querySelector('#zoomVignette').style.display=zoom?'block':'none';const wanted=zoom?this.settings.fov*.35:this.settings.fov;this.camera.fov=V.lerp(this.camera.fov,wanted,Math.min(1,dt*12));this.camera.updateProjectionMatrix();document.querySelector('#underwaterOverlay').style.display=this.player.headWater?'block':'none';this.hudTimer-=dt;if(this.hudTimer<=0){this.hudTimer=.1;this.ui.refreshHUD()}this.debugUpdate(this.fps)}
}
V.Game=Game;
})();
