(function(){
'use strict';const V=window.Voidlands;
class Panorama{
 constructor(app){this.app=app;this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0x6f9bb1);this.camera=new THREE.PerspectiveCamera(70,innerWidth/innerHeight,.1,300);this.camera.position.set(18,15,18);this.scene.fog=new THREE.Fog(0x6f9bb1,30,95);this.group=new THREE.Group();this.scene.add(this.group);this.hemi=new THREE.HemisphereLight(0xcbe6ff,0x38452f,1.25);this.sun=new THREE.DirectionalLight(0xffedbd,1.2);this.sun.position.set(20,30,10);this.scene.add(this.hemi,this.sun);const colors=[0x5f9d56,0x765b3d,0x777c80,0xd3bd7f,0x47734a,0x9dbbc1];for(let z=-14;z<=14;z++)for(let x=-14;x<=14;x++){const h=Math.floor(3+Math.sin(x*.3)*2+Math.cos(z*.23)*2+V.Noise.fbm2(x*.11,z*.11,8844,3)*3);for(let y=0;y<h;y++){if(y<h-2&&Math.random()>.18)continue;const geo=new THREE.BoxGeometry(1,1,1),mat=new THREE.MeshLambertMaterial({color:y===h-1?colors[0]:y>h-3?colors[1]:colors[2]});const m=new THREE.Mesh(geo,mat);m.position.set(x,y,z);this.group.add(m)}if(Math.random()>.965){for(let y=h;y<h+4;y++){const m=new THREE.Mesh(new THREE.BoxGeometry(.6,1,.6),new THREE.MeshLambertMaterial({color:0x68472c}));m.position.set(x,y,z);this.group.add(m)}const crown=new THREE.Mesh(new THREE.BoxGeometry(3,2.4,3),new THREE.MeshLambertMaterial({color:colors[4]}));crown.position.set(x,h+4,z);this.group.add(crown)}}this.water=new THREE.Mesh(new THREE.PlaneGeometry(80,80),new THREE.MeshLambertMaterial({color:0x3f83b1,transparent:true,opacity:.75}));this.water.rotation.x=-Math.PI/2;this.water.position.y=2.6;this.scene.add(this.water);this.t=0;this.active=true;this.setVibrant(!!app.settings.vibrantVisuals);this.loop()}
 setVibrant(enabled){const v=!!enabled;this.scene.background.set(v?0x63aee0:0x6f9bb1);this.scene.fog.color.set(v?0x63aee0:0x6f9bb1);this.hemi.intensity=v?1.48:1.25;this.sun.intensity=v?1.5:1.2;this.water.material.color.set(v?0x3c9bd0:0x3f83b1);this.water.material.opacity=v?.82:.75;this.app.canvas.classList.toggle('vibrant-visuals',v);this.app.renderer.toneMapping=v?THREE.ACESFilmicToneMapping:THREE.NoToneMapping;this.app.renderer.toneMappingExposure=v?1.08:1}
 loop(){if(!this.active)return;requestAnimationFrame(()=>this.loop());this.t+=.0015;this.camera.position.set(Math.cos(this.t)*27,14+Math.sin(this.t*.4)*2,Math.sin(this.t)*27);this.camera.lookAt(0,5,0);this.water.position.y=2.6+Math.sin(this.t*8)*.04;this.app.renderer.render(this.scene,this.camera)}
 stop(){this.active=false;this.scene.traverse(o=>{if(o.geometry)o.geometry.dispose();if(o.material)o.material.dispose()})}
}
class App{
 constructor(){this.canvas=document.querySelector('#gameCanvas');this.storage=new V.StorageManager();this.settings=this.storage.settings;this.audio=new V.AudioSystem(this.settings);this.renderer=new THREE.WebGLRenderer({canvas:this.canvas,antialias:this.settings.graphics!=='fast',alpha:false,powerPreference:'high-performance'});this.renderer.setSize(innerWidth,innerHeight,false);this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));this.renderer.outputEncoding=THREE.sRGBEncoding;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.toneMapping=this.settings.vibrantVisuals?THREE.ACESFilmicToneMapping:THREE.NoToneMapping;this.renderer.toneMappingExposure=this.settings.vibrantVisuals?1.08:1;this.canvas.classList.toggle('vibrant-visuals',!!this.settings.vibrantVisuals);this.game=null;this.ui=new V.UI(this);this.panorama=new Panorama(this);window.addEventListener('resize',()=>{if(!this.game){this.renderer.setSize(innerWidth,innerHeight,false);this.panorama.camera.aspect=innerWidth/innerHeight;this.panorama.camera.updateProjectionMatrix()}});document.addEventListener('pointerdown',()=>this.audio.resume(),{once:true})}
 createFromForm(){const v=id=>document.querySelector('#'+id),w=this.storage.create({name:v('worldName').value.trim()||'New World',seed:v('worldSeed').value,mode:v('gameMode').value,difficulty:v('difficulty').value,worldType:v('worldType').value,structures:v('structures').checked,bonusChest:v('bonusChest').checked});this.startWorld(w)}
 async startWorld(w){if(w.hardcoreDead){this.ui.toast('This Hardcore world has been lost. Recreate it to play again.');return}this.audio.resume();if(this.panorama){this.panorama.stop();this.panorama=null}this.ui.qa('.screen').forEach(x=>x.classList.remove('active'));this.game=new V.Game(this,w);await this.game.initialize()}
 returnToTitle(){document.querySelector('#hud').classList.add('hidden');this.ui.selectedWorld=null;this.ui.renderWorlds();this.ui.show('titleScreen');this.panorama=new Panorama(this)}
}
function boot(){if(!window.THREE){const l=document.querySelector('#loadingScreen');l.classList.remove('hidden');document.querySelector('#loadingText').textContent='Three.js could not load';document.querySelector('#loadingTip').textContent='Connect to the internet once, or place three.min.js locally and update index.html.';return}window.voidlandsApp=new App()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
